### ISSUE TITLE
project_panel::ToggleExpanded not working in keymap.json

### ISSUE THREAD

**Issue by stormasm** [zed-industries/feedback#111]
**Describe the bug**

In the atom editor toggling the Project Panel 
uses the keymap binding Cmd-\

This is something I use all the time...

I want to see the tree view of the files 
select the file I want to edit
and then I want the tree view to be hidden

Having the icon on the left side at the bottom of the editor
is handy but I don't want to be clicking around on the mouse a lot.

I would like to reproduce this functionality in Zed
as I use the atom editor a lot 
as well as Zed now too :)

So I would like them both to be the same binding...

Other folks coming from Atom may feel the same way,
so just my 2 cents not sure why you are using cmd-shift-!
which seems like a very convoluted key stroke, but that is
not the point of this issue.

in keymap.json when I put this in my file

[
    {
        "context": "ProjectPanel",
        "bindings": {
            "cmd-\\\\": "project_panel: :ToggleExpanded",
        }
    }
]

Nothing happens as this does not seem to work and the
fixed binding (cmd-shift-!) is still in place and it works.

I tried a different binding just because I wasn't sure about the
"cmd-\\\\" syntax but that did not work either

[
    {
        "context": "ProjectPanel",
        "bindings": {
            "cmd-i": "project_panel: :ToggleExpanded",
        }
    }
]

Please let me know as I may be doing something wrong
with keymap.json or the project_panel command may not
be correct...

Also, question, once you change the keymap.json file...

How do you get Zed to run that ?

Do I have to get out of Zed completely and come back in ?

thank you....

**Comment by JosephTLyons** [comment]
I'm not entirely sure, since I haven't customized this action, but does any of this work for you?

```json
{
        "context": "Workspace",
        "bindings": {
            "cmd-1": [
                "workspace::ToggleSidebarItemFocus",
                {
                    "side": "Left",
                    "item_index": 0
                }
            ],
            "cmd-shift-!": [
                "workspace::ToggleSidebarItem",
                {
                    "side": "Left",
                    "item_index": 0
                }
            ],
            "cmd-9": [
                "workspace::ToggleSidebarItemFocus",
                {
                    "side": "Right",
                    "item_index": 0
                }
            ],
            "cmd-shift-(": [
                "workspace::ToggleSidebarItem",
                {
                    "side": "Right",
                    "item_index": 0
                }
            ]
        }
    },
```

**Comment by JosephTLyons** [comment]
While I wasn't able to get it to work with `cmd-\\`, I was able to get it to work with `cmd-i` using:

```json
{
        "context": "Workspace",
        "bindings": {
            "cmd-i": [
                "workspace::ToggleSidebarItem",
                {
                    "side": "Left",
                    "item_index": 0
                }
            ]
        }
    }
```

**Comment by stormasm** [comment]
@JosephTLyons Thanks for the feedback and quick response...

I am on Zed 0.39.0

All of the [default key map bindings](https://zed.dev/ref/default.json) work.

But NONE of my custom keybindings are working for me...

```rust
{
    "context": "Workspace",
    "bindings": {
        "cmd-2": [
            "workspace::ToggleSidebarItemFocus",
            {
                "side": "Left",
                "item_index": 0
            }
        ],
        "cmd-i": [
            "workspace::ToggleSidebarItem",
            {
                "side": "Left",
                "item_index": 0
            }
        ],
        "cmd-8": [
            "workspace::ToggleSidebarItemFocus",
            {
                "side": "Right",
                "item_index": 0
            }
        ],
        "cmd-shift-i": [
            "workspace::ToggleSidebarItem",
            {
                "side": "Right",
                "item_index": 0
            }
        ],
    }
}

```

**Comment by stormasm** [comment]
To get things to try and work...
After I set my keymap.json file...
I completely exit out of Zed...
And then bring it back up...

**Comment by JosephTLyons** [comment]
> @JosephTLyons Thanks for the feedback and quick response...
> 
> I am on Zed 0.39.0
> 
> All of the [default key map bindings](https://zed.dev/ref/default.json) work.
> 
> But NONE of my custom keybindings are working for me...
> 
> ```rust
> {
>     "context": "Workspace",
>     "bindings": {
>         "cmd-2": [
>             "workspace::ToggleSidebarItemFocus",
>             {
>                 "side": "Left",
>                 "item_index": 0
>             }
>         ],
>         "cmd-i": [
>             "workspace::ToggleSidebarItem",
>             {
>                 "side": "Left",
>                 "item_index": 0
>             }
>         ],
>         "cmd-8": [
>             "workspace::ToggleSidebarItemFocus",
>             {
>                 "side": "Right",
>                 "item_index": 0
>             }
>         ],
>         "cmd-shift-i": [
>             "workspace::ToggleSidebarItem",
>             {
>                 "side": "Right",
>                 "item_index": 0
>             }
>         ],
>     }
> }
> ```

Here's how mine is currently set up:

```json
[
    {
        "context": "Editor",
        "bindings": {
            "cmd-d": "editor::DuplicateLine",
            "shift-alt-up": "editor::AddSelectionAbove",
            "shift-alt-down": "editor::AddSelectionBelow"
        }
    },
    {
        "bindings": {
            "cmd-alt-,": "zed::OpenKeymap"
        }
    }
]
```

I notice that yours doesn't have the outermost `[` and `]`.  Is that the case for what is actually in your file?

**Comment by stormasm** [comment]
@JosephTLyons Thank you kindly for your continued patience on this issue, I went ahead and modified my file accordingly and put in the outer braces and unfortunately it made no difference.  NONE of the four key bindings in the file actually work, whereas all of the default key bindings are still in play.

Based on your hypothesis I went ahead and grabbed the whole 
https://zed.dev/ref/default.json file and then went ahead and just individually
modified the 4 fields in the above file and the default ones are the only ones that work whereas my bindings don't kick in.

I even went ahead and modified this key binding which works fine as is...

```rust
            "cmd-k left": [
                "pane::Split",
                "Left"
            ],
```

Just to see if something would work and it failed as well...

After of course bringing down Zed and bringing it back up after the modification.

Could it be how I am bringing up Zed ?  
Because the keybindings are not kicking in...
I am double clicking on the Icon in my task bar...

**Comment by JosephTLyons** [comment]
> @JosephTLyons Thank you kindly for your continued patience on this issue, I went ahead and modified my file accordingly and put in the outer braces and unfortunately it made no difference. NONE of the four key bindings in the file actually work, whereas all of the default key bindings are still in play.
> 
> Based on your hypothesis I went ahead and grabbed the whole https://zed.dev/ref/default.json file and then went ahead and just individually modified the 4 fields in the above file and the default ones are the only ones that work whereas my bindings don't kick in.
> 
> I even went ahead and modified this key binding which works fine as is...
> 
> ```rust
>             "cmd-k left": [
>                 "pane::Split",
>                 "Left"
>             ],
> ```
> 
> Just to see if something would work and it failed as well...
> 
> After of course bringing down Zed and bringing it back up after the modification.
> 
> Could it be how I am bringing up Zed ? Because the keybindings are not kicking in... I am double clicking on the Icon in my task bar...

Hmmm, this is really strange.  You shouldn't even have to close and open Zed.  The new keybindings should kick in on saving the keymap file.  Just to be entirely sure, you are pasting these bindings into the `~/.zed/keymap.json` file?  You aren't accidentally putting these into `~/.zed/keymap.json`?  

I know we can figure this out, but I'm at a bit of a loss currently - maybe a screen capture video (using Quicktime, or whatever) might help narrow it down.

**Comment by iamnbutler** [comment]
I brought this up with the team, hopefully someone can pop in shortly to see what is up!

**Comment by JosephTLyons** [comment]
> @JosephTLyons I just noticed [in the docs](https://zed.dev/docs/key-bindings) it states the following....
> 
> **_There are some key bindings that can't be overridden; we are working on an issue surrounding this._**

This shouldn't be the issue, since none of the items are working for you.

> @JosephTLyons correct, the file is located in the same spot as my settings.json file which is working fine....
> 
> Oh by the way 👍
> 
> Here is my settings.json file
> 
> ```rust
> {
>     "language_overrides": {
>         "Rust": {
>             "enable_language_server": false
>         }
>     }
> }
> ```
> 
> could it be related to the fact that my rust analyzer etc is turned off ?

This should also have no effect on the custom keybindings.

If you end up having a few extra minutes, pop open Quicktime Player and shoot a screen recording with `File > New Screen Recording` and go through the full process of trying to edit the keybinding, saving the file, and trying the keybinding.  There surely could be some bug here preventing you from being able to customize something or it could be some small minute thing that is being missed, either way, I'm a bit lost and a video would help a bunch.

**Comment by stormasm** [comment]
@JosephTLyons the only items I have tested are the 

workspace::ToggleSidebarItem
workspace::ToggleSidebarItemFocus

both left and right

plus the other one mentioned above...

are those on the list of what is referred to in the docs as not working...

Unfortunately I am heading out fairly soon for the day...
So if I do the video or we do the collaboration it will have to be
tomorrow or Friday...

rather than doing a video / why not try out the collaboration feature ?
that should accomplish the same task right ?
although I have not used it before...

**Comment by JosephTLyons** [comment]
> @JosephTLyons the only items I have tested are the
> 
> workspace::ToggleSidebarItem workspace::ToggleSidebarItemFocus
> 
> both left and right
> 
> plus the other one mentioned above...
> 
> are those on the list of what is referred to in the docs as not working...

Those should work.  In this video, you can see me toggling the left sidebar item with the default command of `cmd-shift-!` and `cmd-i` does not work.  I then go into the keymap.json file, paste in the snippet to override that binding to use `cmd-i`, save the file, and the keybinding works:

https://user-images.githubusercontent.com/19867440/175103720-c40509fb-39fc-4b84-8a46-92e5a456d27b.mov

**Comment by Kethku** [comment]
I'm taking a look now. I've copied your keymap.json into mine and have reproduced the issue. Investigating

**Comment by JosephTLyons** [comment]
> Ok here is the video... You will see that when I hit the cmd-shift-i nothing happens And when I hit the command-shift-! it works...
> 
>  zed5.mov

Try using an uppercase i

`cmd-shift-I`

**Comment by Kethku** [comment]
Can you try capitalizing `I` in `cmd-shift-I`?

**Comment by stormasm** [comment]
@Kethku @JosephTLyons 
That did not work...
I also tried just cmd-i as well...

Are you all both sure that it's not on the list of keymap bindings that do not work
as denoted in the docs...

As well as, you are both sure it has nothing to do with my settings.json
file see above ?  Not running the language server / rust analyzer...

Again, many thanks for looking into this...

**Comment by JosephTLyons** [comment]
> @Kethku @JosephTLyons 
> 
> Are you all both sure that it's not on the list of keymap bindings that do not work
> 
> as denoted in the docs...

I posted a video earlier that demonstrated me customizing the keybinding for toggling the left sidebar, so it definitely is one that is customizable.

**Comment by stormasm** [comment]
ok so here is some progress on this issue...
my custom keybindings are indeed working !  yeh...

I swapped out / switched ctrl-e and ctrl-a and it just worked...
And I switched them back and it worked...
I did not have to restart when I made the change it just kicked in....

So I now know its not my settings.json file either...

So my suspicion is those specific ones we are addressing are BROKEN.
On the downloaded version of Zed 0.39.0

just my 2 cents...
and since I can't look at the code (just a guess)...

**Comment by stormasm** [comment]
the keymap.json file I am starting with 
prior to making any changes is this one
https://zed.dev/ref/default.json

another reason it may be broken is because every time I make the change the 

cmd-shift-! continues to work...

why isn't cmd-shift-! in the keymap.json file ?

**Comment by stormasm** [comment]
hold on ! I might now know what is up....

**Comment by JosephTLyons** [comment]
> 

Hmm, I copied and pasted that entire file into Zed as well and it seems it doesn't work right off the bat.  I'm wondering if something has changed since that file was uploaded.  I was able to edit it into working:

```json
[
    {
        "context": "Workspace",
        "bindings": {
            "cmd-shift-I": [
                "workspace::ToggleSidebarItem",
                {
                    "side": "Left",
                    "item_index": 0
                }
            ]
        }
    }
]
```

**Comment by JosephTLyons** [comment]
One thing for sure, all this sort of points to having some sort of validation for the config.

**Comment by JosephTLyons** [comment]
> so I just checked and downloaded
> https://zed.dev/ref/default.json
> again just to make sure...
> and I switched the
> cmd-shift-!
> to something else like
> cmd-shift-I
> or
> cmd-j
> and the cmd-shift-! continues to work,
> so it is not picking it up...

One thing to note here is that overriding a keybinding does **not** currently de-register the old keybinding.  If you successfully override one, the old one will still exist, unless you specifically override the old one as well with a new action.

**Comment by stormasm** [comment]
I copied and pasted your fix into keymap.json

**Comment by stormasm** [comment]
```rust
[
    {
        "context": "Workspace",
        "bindings": {
            "cmd-shift-I": [
                "workspace::ToggleSidebarItem",
                {
                    "side": "Left",
                    "item_index": 0
                }
            ]
        }
    }
]
```

**Comment by stormasm** [comment]
That is the only thing in my keymap.json file

**Comment by JosephTLyons** [comment]
Something I did was initialize a git repo at `/Users/josephlyons/.zed`, so that I can make sure I don't accidentally change any settings or keymap configurations and sync my settings between computers.

https://github.com/JosephTLyons/.zed

**Comment by stormasm** [comment]
@JosephTLyons thank you so much for hanging in there with me...
We can rest easy this evening !!!

**Comment by stormasm** [comment]
Yes, I have a dotfiles on my github where I will put this file so we have it....
very, very cool !!
💯

**Comment by JosephTLyons** [comment]
> @JosephTLyons thank you so much for hanging in there with me...
> We can rest easy this evening !!!

No problem, glad it is now working for you :)

**Comment by stormasm** [comment]
And for the record on this issue,
this also works.
Which was my original goal was to mimic the way atom works...

**Comment by stormasm** [comment]
```rust
[
    {
        "context": "Workspace",
        "bindings": {
            "cmd-\\": [
                "workspace::ToggleSidebarItem",
                {
                    "side": "Left",
                    "item_index": 0
                }
            ]
        }
    }
]
```

**Comment by JosephTLyons** [comment]
> ```rust
> [
>     {
>         "context": "Workspace",
>         "bindings": {
>             "cmd-\\": [
>                 "workspace::ToggleSidebarItem",
>                 {
>                     "side": "Left",
>                     "item_index": 0
>                 }
>             ]
>         }
>     }
> ]
> ```

Oops, I closed this issue out forgetting that this was originally about `cmd-\\` - luckily, it works!  I just tried it on my end too.  Nice!
