### ISSUE TITLE
Ruby support

### ISSUE THREAD

**Issue by holman** [zed-industries/feedback#113]
Gonna throw the hat in the ring for support for good ol' Ruby.

**Comment by gobijan** [comment]
There are currently two major language servers using LSP for Ruby:

**Solargraph**
Maintained for quite some time. Works okayish (has some problems with Rails and finding references in gems).
https://github.com/castwide/solargraph

**Shopify Ruby LSP**
New kid on the block directly from Shopify.
https://github.com/Shopify/ruby-lsp

**Comment by Atelier-Mirai** [comment]
We hope that Ruby / Ruby on Rails will be supported.

**Comment by JosephTLyons** [comment]
I'm going to suggest we use Rubyfmt:

https://github.com/penelopezone/rubyfmt

**Comment by maxbrunsfeld** [comment]
The next release of Zed will have basic support for ruby. I'm leaving this open though, because we haven't yet integrated a ruby language server or ERB support, though we plan to add those soon.

**Comment by attilagyorffy** [comment]
Currently running Zed 0.62.8 and not getting any syntax highlighting in Zed. Can you advise whether this has made it to the release after all or if there's any configuration necessary to get it to work. Anything I could help with? Thanks in advance.

**Comment by maxbrunsfeld** [comment]
Basic ruby support will land in zed 0.63.

**Comment by maxbrunsfeld** [comment]
ERB support will land in Zed 0.65.

**Comment by maxbrunsfeld** [comment]
Zed 0.65 will also provide code intelligence for ruby using Solargraph. For now, you'll need to install the `solargraph` yourself using a tool like Bundler, such that it is available on your `PATH` when loading your shell. I think this is in line with how Solargraph recommends that people install and use the tool. There is a fair bit of complexity to installing Ruby gems as self-contained binaries, so we opted to not try to automate that process from the Zed app.

**Comment by attilagyorffy** [comment]
@maxbrunsfeld Thanks for the update. Solargraph may be added to a Ruby app's `Gemfie` (via bundler) or it may be simply installed into local Rubygems (via a `gem install solargraph` command). I do wonder though, how is Zed handling different versions of Ruby being available on a single system? (and therefore knowing how to access the installed solargraph gem within it?)

**Comment by maxbrunsfeld** [comment]
> I do wonder though, how is Zed handling different versions of Ruby being available on a single system? (and therefore knowing how to access the installed solargraph gem within it?)

Thanks for bringing this up. Right now, Zed is simply looking for `solargraph` using the `PATH` environment variable as configured by your default shell initialization script. So for example, if you use `rbenv` to manage your Ruby installations, and you run `rbenv init` in your `.zshrc`/`.bash_profile`, Zed would pick up whichever ruby version is currently set via the `rbenv global` command.

Now that you've brought that up, I'm realizing that we probably need to make this more sophisticated. I'm wondering if you have suggestions on the lowest-configuration way that we could do this. Should Zed be looking at `.ruby-version` and figuring out the path to `solargraph` based on that? Does there need to be a setting for where `solargraph` is installed?

**Comment by attilagyorffy** [comment]
@maxbrunsfeld Thanks for the response! I'm more than happy to help if I can, especially around Ruby support and I do believe that the current approach works for the majority of users. (Especially given that Zed is targeting macOS users and based on experience, most Rubyists use a [version](https://github.com/rbenv/rbenv) [manager](https://rvm.io) in [one](https://github.com/postmodern/chruby) [form](https://github.com/postmodern/chruby) or [another](https://github.com/asdf-vm/asdf-ruby).) Even with numerous version managers available, afaik the community has settled around a convention that these will use the `.ruby-version` file in each project root directory and will respect that. _(This needs double checking but I'm almost certain that this is the case though)_

I've created a tiny demo for this:

<img width="1800" alt="Screenshot 2022-11-21 at 21 33 36" src="https://user-images.githubusercontent.com/9091/203154451-e52aec87-a0a2-4eff-a298-b0de0cdfa10c.png">

Notice how I rely solely on rbenv being set up in the shell itself and how it's more than capable of choosing the right version of Ruby without any configuration. Following up on that logic, as long as $PATH is currently set up, Zed should also be able to use the right version of Ruby.

However, there might be cases where there are multiple versions of solargraph installed under the same Ruby version and even specified in a project's Gemfile:

```ruby
# Taken from the official docs at https://github.com/castwide/solargraph
gem "solargraph", "~> 0.47.2"
```

In this case I would expect Zed to take the "bundled" version of solar graph into account and therefore imho solar graph should be running in a bundled environment. There are two ways to achieve this:

1) Explicitly running solargraph via bundler exec: `bundle exec solargraph` 
2) Or using the provided bin stubs in the project under `./bin/solargraph`.

Example of the above:

<img width="1800" alt="Screenshot 2022-11-21 at 21 51 33" src="https://user-images.githubusercontent.com/9091/203156361-cd1c831a-6887-463a-89c2-0a83f07f343c.png">

Being able to check whether a specific version of solargraph is bundled can be done by simply trying to query the version of solargraph in the current bundler context. (Doing so by getting the version should have a minimal overhead):
 
<img width="1800" alt="Screenshot 2022-11-21 at 21 57 48" src="https://user-images.githubusercontent.com/9091/203156858-a509ee2f-9f91-4597-91b4-d7dc832aebc9.png">

**So to sumarize:**

I believe Zed should ideally follow the [Convention Over Configuration paradigm](https://en.wikipedia.org/wiki/Convention_over_configuration) and be smart about the above without the need of any configuration necessary. I believe a sensible priority (from higher to lower) would be the following:

* Use the solargraph bin stub if present (`./bin/solargraph`)
* Use the bundled version of solargraph if specified by the bundler context (see method described above)
* Use the matching `solargraph` in the $PATH (which should match the version of Ruby -> This is the current implementation if I understand correctly)
* Fail with a helpful error message, and with a link to a publicly available piece that helps setting things up
 
Convention over configuration also specifies that in any case whereby in need, a developer should be able to explicitly configure Zed according to their needs. This obviously depends on how Zed will use configuration as a whole. Some editors have special name spacing for extensions, there are some examples in the [VS Code extension](https://github.com/castwide/vscode-solargraph#extension-settings) that might be useful [here](https://github.com/castwide/vscode-solargraph#extension-settings).

Let me know if you have any more questions or if I can help. :)

**Comment by maxbrunsfeld** [comment]
@attilagyorffy I opened a separate issue for this SolarGraph suggestion https://github.com/zed-industries/feedback/issues/730. If other people have thoughts or interest in this change specifically, please comment, subscribe and 👍  that issue. Thank you!

**Comment by mloughran** [comment]
I was very pleased to discover that it's trivial to use an external formatter. For example to use [rufo](https://github.com/ruby-formatter/rufo) add the following to settings.json:
```json
"language_overrides": {
    "Ruby": {
        "formatter": {
            "external": {
                "command": "rufo",
                "arguments": [
                    "-x"
                ]
            }
        }
    }
}
```

**Comment by kucho** [comment]
If someone gets here looking for a Rubocop example, use one of these:

#### with bundler

```
    "language_overrides": {
        "Ruby": {
            "format_on_save": "on",
            "formatter": {
                "external": {
                    "command": "./bin/bundle",
                    "arguments": [
                        "exec",
                        "rubocop",
                        "--auto-correct",
                        "--stdin",
                        "corrected.rb",
                        "--stderr"
                    ]
                }
            }
        }
    }
```

#### without bundler

```
    "language_overrides": {
        "Ruby": {
            "format_on_save": "on",
            "formatter": {
                "external": {
                    "command": "rubocop",
                    "arguments": [
                        "--auto-correct",
                        "--stdin",
                        "corrected.rb",
                        "--stderr"
                    ]
                }
            }
        }
    }
```

**Comment by JosephTLyons** [comment]
> If someone gets here looking for a Rubocop example, use one of these:
> 
> #### with bundler
> ```
>     "language_overrides": {
>         "Ruby": {
>             "format_on_save": "on",
>             "formatter": {
>                 "external": {
>                     "command": "./bin/bundle",
>                     "arguments": [
>                         "exec",
>                         "rubocop",
>                         "--auto-correct",
>                         "--stdin",
>                         "corrected.rb",
>                         "--stderr"
>                     ]
>                 }
>             }
>         }
>     }
> ```
> 
> #### without bundler
> ```
>     "language_overrides": {
>         "Ruby": {
>             "format_on_save": "on",
>             "formatter": {
>                 "external": {
>                     "command": "rubocop",
>                     "arguments": [
>                         "--auto-correct",
>                         "--stdin",
>                         "corrected.rb",
>                         "--stderr"
>                     ]
>                 }
>             }
>         }
>     }
> ```

Hey @kucho, this seems like it would be a killer tip for our `Share a Tip` section in our forum.  Would you mind posting it there for others to discover?

https://github.com/zed-industries/community/discussions/categories/share-a-tip

**Comment by JosephTLyons** [comment]
Would you mind if I posted this as a tip @kucho?

**Comment by kucho** [comment]
> Would you mind if I posted this as a tip @kucho?

Please do it. Sorry I didn't reply earlier, I've been very busy this week.
