### ISSUE TITLE
Open any file from tree view with Enter key

### ISSUE THREAD

**Issue by exalted** [zed-industries/feedback#12]
I wish after having `Cmd-1`-ed to the file tree view and moved with up/down arrow keys to the file I want, hitting the `Enter` key would open that file.

When I tested Zed a while back, I realized left arrow key on a file used to do just that, but I don’t know, it wasn’t all that intuitive to me at first, and in v0.37.0 this doesn't work either. :)

**Comment by ruijdacd** [comment]
I would expect the same behaviour, although I'm used to using `space` for that and `enter` for renaming.

I did notice that there is a keybind for this called `project_panel::Open`, however when setting it, it seems to break the project panel keymaps config altogether.

**Comment by exalted** [comment]
No strong opinion about space VS Enter here. Either works! 😉

**Comment by JosephTLyons** [comment]
Closed via https://github.com/zed-industries/zed/pull/1183
