### ISSUE TITLE
Go to definition via command click

### ISSUE THREAD

**Issue by futurepaul** [zed-industries/feedback#120]
**Is your feature request related to a problem? Please describe.**

I don't use my function keys very often. In VS Code I typically do go-to-definition by command + clicking on a method.

**Describe the solution you'd like**

Holding command turns code into a clickable "link" to its definition.

**Describe alternatives you've considered**

I could be more disciplined about using the keyboard to do this.

**Comment by JosephTLyons** [comment]
Hi @futurepaul, I believe one of the Zed devs might've actually begun work on this, though I'm not sure when it might land or if there were any issues along the way that slowed it down, but its definitely on the roadmap.

**Comment by JosephTLyons** [comment]
Closed via https://github.com/zed-industries/zed/pull/1237
