### ISSUE TITLE
Removing a file from project shouldn't read as "remove folder from project"

### ISSUE THREAD

**Issue by exalted** [zed-industries/feedback#13]
`settings.json` in the screenshot below is a file and not a folder. Makes sense? 🙏 

![CleanShot 2022-06-08 at 11 51 02@2x](https://user-images.githubusercontent.com/314398/172587876-ced6bd0c-412c-4174-98c5-ed63d528dcad.png)

**Comment by iamnbutler** [comment]
I think this is a weird specific case with `settings.json` since it is considered a "hidden worktree". These soon won't get added to the project at all. I'll close this out when that is fixed, but let me know if you see this with any other files!

**Comment by exalted** [comment]
@iamnbutler sure thing, thanks! I am reporting stuff as I see them, but this one, specifically, is by no means is an "issue"…

**Comment by iamnbutler** [comment]
Thanks for the diligent feedback!

**Comment by as-cii** [comment]
We should replace `Remove Folder from Project` with `Remove from Project`. Also, ensure the menu item labels match the above text.

**Comment by as-cii** [comment]
The fix for this will go out with the next release. Thanks!
