### ISSUE TITLE
Unfocusing the new file input field causes it to break

### ISSUE THREAD

**Issue by tom-hewitt** [zed-industries/feedback#132]
**Describe the bug**
After unfocusing the new file input field, it remains on the screen and doesn't react when clicked on. It remains even after collapsing the parent folder.

**To reproduce**
RIght-click on a folder, and click "New File". Before confirming the name of the new file, click on a different file.

**Expected behavior**
I would expect the input field to disappear.

**Screenshots**
https://user-images.githubusercontent.com/47860067/175380023-1e347d3d-b1db-4d89-998d-e7f9a285e2e8.mov

**Environment:**
Zed 0.39.0 – /Applications/Zed.app
macOS 12.0.1
architecture arm64

**Comment by as-cii** [comment]
I tried reproducing this several times but to no avail. This was reported in v0.39.0, is there any chance you could give v0.50.0 a go and see if it's still an issue?

I am going to close this for now, but please feel free to re-open if you can still reproduce in the latest version! 🙏

**Comment by tom-hewitt** [comment]
Seems to be no longer be an issue in v0.50.0!
