### ISSUE TITLE
Python auto-indent does not work

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/feedback#136]
**Screenshots**
https://user-images.githubusercontent.com/19867440/175428145-6c998f82-2200-46a0-a578-36417e04334f.mov

**Environment:**
Zed 0.40.0 – /Applications/Zed.app
macOS 12.4
architecture x86_64

**Comment by maxbrunsfeld** [comment]
@JosephTLyons I can't get that video to load. Can you post a code snippet where the auto indent isn't working as expected?

**Comment by JosephTLyons** [comment]
> @JosephTLyons I can't get that video to load. Can you post a code snippet where the auto indent isn't working as expected?

Hmm, weird.  It doesn't play for me either.  I don't think GitHub likes videos that run too long.  Anyway, I'm not able to get auto-indent to work anywhere.  Here is a new file called `main.py`:

```python
def main():
    while True:
        pass


if __name__ == "__main__":
    main()
```

I had to manually indent everything that is shown here

**Comment by maxbrunsfeld** [comment]
Oh, I see the problem now. When testing, I was always editing existing code, not typing out new empty functions and such from scratch. Sorry for the brokenness.

**Comment by JosephTLyons** [comment]
No problem, seems like Tree Sitter may not be looking for `:` or something
