### ISSUE TITLE
A command to open the Zed.log directly in Zed

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/feedback#148]
I think having a command palette action to open the Zed log, within Zed, would be convenient for testers who are trying to file bug reports that require pasting in some log lines.  I don't think it needs a keybinding, as that would just add more things users could trip over during normal coding - just a command palette action would do the trick.

**Comment by maxbrunsfeld** [comment]
Let's add a recognizable log line when zed starts up, so that we can populate the editor with *the current session's* logs.

**Comment by JosephTLyons** [comment]
> Let's add a recognizable log line when zed starts up, so that we can populate the editor with _the current session's_ and the previous session's logs.

This comment makes me wonder if the log files should just be broken up into new files based on sessions - it would break up a single massive file into smaller, more manageable files.  You wouldn't have to log anything specific to the log file to know when a session started and ended - for this feature, you'd just grab the last 2 files.  And in the future, Zed could have some setting for how many sessions worth of logs to store (some auto-delete feature to only save the last n files, but delete anything before that).  Idk, just an idea.  Might be too convoluted and hair-brained.

**Comment by JosephTLyons** [comment]
Then again, Idk what my that would mean for opening the current sessions log file and the previous sessions log file... using multiple tabs?  Idk.
