### ISSUE TITLE
Scrollbars

### ISSUE THREAD

**Issue by mikayla-maki** [zed-industries/feedback#165]
**Is your feature request related to a problem? Please describe.**

I noticed that Zed doesn't have any scrollbars anywhere. This seems like a strange omission given their ubiquity elsewhere.

**Describe the solution you'd like**

For scrollable areas to have some kind of scroll bar associated with them, preferably ephemeral so they don't clutter the UI too much.

**Describe alternatives you've considered**

N/A

**Screenshots**

N/A

**Comment by JosephTLyons** [comment]
Yes!  Not having scrollbars has been killing me a bit inside 🤣.  Really would love to get these.

**Comment by mikayla-maki** [comment]
Mouse based interaction definitely needs some quality time focus for Zed.

**Comment by mikayla-maki** [comment]
Properly implementing scrolling that *feels* perfect on a touch pad, while also supporting other devices has a lot of weird complexity. 

To properly emulate the physics of a scroll bar requires:
- [ ] Scrolling acceleration for navigating large files.
- [ ] Kinetic scrolling for easing acceleration
- [ ] Elastic scrolling when at the ends

The input elements are:
- [ ] Scrollbar - Produce arbitrarily scaled scrolls based on the ratio of content length to the viewport.
- [ ] Mouse wheel - Typically produce line based units which need to be converted to pixels
- [ ] External navigation (e.g. terminal output appended, jump to a location in a file) - Context dependent
- [ ] Touchpad / Trackpad - Should produce exact pixel deltas, in practice often produce line deltas because windows.

If performance proves tricky, maybe consider using blit acceleration.

**Comment by und3fined** [comment]
Scrollbars can be superfluous.
But Minimap is better solution for Scrollbars, with a touch screen, touchpad/trackpad it's friendly

**Comment by kevinsjoberg** [comment]
@und3fined I always disable the minimap (I can’t stand it). And given the feedback in #263 , I’m not alone.

**Comment by rsms** [comment]
Scrollbars are a must–have. Two good reasons:
- So you can tell where you are relative to file length
- So you can use a mouse to jump around in a file
A third good reason is that it is an OS standard and let's not fuck with OS standards :–)

**Comment by aexvir** [comment]
just please follow the os settings and let us have them only active during scrolling and not visible 100% of the time 🙏🏻 
<img width="417" alt="Screenshot 2022-08-09 at 21 42 56" src="https://user-images.githubusercontent.com/8055505/183747261-fab7e5d9-863c-4652-b7b9-64488d75bb8a.png">

**Comment by iamnbutler** [comment]
> just please follow the standard macos settings and let us also have the option to show them only when scrolling and not visible 100% of the time 🙏🏻 <img alt="Screenshot 2022-08-09 at 21 42 56" width="417" src="https://user-images.githubusercontent.com/8055505/183747261-fab7e5d9-863c-4652-b7b9-64488d75bb8a.png">

We should support these settings. I can't guarantee we can read the setting FROM macOS that you currently have set (not an engineer), but at the least we will have at least have [`when scrolling`|`always`].

**Comment by AlexDaniel** [comment]
> Two good reasons:
>
>    So you can tell where you are relative to file length
>    So you can use a mouse to jump around in a file

Scrollbars also visualize the size of the file (long files have a shorter scroll bars). For that reason, if you go with the “only show when scrolling” implementation, the scroll bar should also appear briefly when opening a new file.

**Comment by sifbiri** [comment]
Would be nice to have scrollbar in bottom status bar (where line/column number appear) just like in screenshot bellow (from Emacs using mlscroll) 

<img width="277" alt="Screen Shot 2022-08-10 at 1 50 49 PM" src="https://user-images.githubusercontent.com/8908139/184017694-48871388-d438-469f-bc18-29b8e363e415.png">
![116825204-38031880-ab5c-11eb-8252-5f60a61f45dd](https://user-images.githubusercontent.com/8908139/184018086-1ea28c3a-924e-41e9-991c-fd9e3e11b739.gif)

**Comment by GKJCJG** [comment]
I see that this is has been marked completed, but it also seems that there are no horizontal scrollbars when text overflows the editor horizontally and doesn't wrap. I think that would be desirable.
