### ISSUE TITLE
Strange cursor blinking

### ISSUE THREAD

**Issue by mikayla-maki** [zed-industries/feedback#167]
**Describe the bug**

Sometimes, the mouse pointer alternates it's set shape. Apparently, this is a tricky and long lasting bug.

**To reproduce**

Unsure, will update when I have a working reproduction.

**Expected behavior**

The cursor should be in one consistent state and shape at every point in time and space.

**Screenshots**

https://user-images.githubusercontent.com/2280405/176258020-ae209c23-c52e-4ecd-a717-d39c00a2b9fa.mov

Thanks to @ChristopherBiscardi for the video.

**Environment:**

N/A

**Comment by mikayla-maki** [comment]
From a month or two ago, @ForLoveOfCats has been running into this and tracking it down, IIRC it seems there's some thrashing over who sets the cursor between Warp and Zed. I had the hypothesis that the alternating was due to the frames scheduled by the cursor blinking also unconditionally setting the cursor shape. There was no further follow up.

**Comment by ForLoveOfCats** [comment]
After moving away from Warp I've not encountered the issue in a month after experiencing it every few days. Given that the issue didn't seem to require Zed being open I'm willing to hesitantly say that the issue I was experiencing was either entirely the result of Warp or the issue was inexplicably resolved as a result of some other change

**Comment by mikayla-maki** [comment]
Well, does Warp play nicely with other programs? If there's something unique about Zed which causes this very specific kind of conflict, it might be good to know.

**Comment by ForLoveOfCats** [comment]
The issue would remain after Zed was entirely exited, only stopping after Warp was closed, which leads me to suspect that on my system Zed was an innocent bystander due to pretty much always being open. I remain open to the possibility that there may be subtle-y different issues at play here though

**Comment by mikayla-maki** [comment]
Ahhhhh, yeah, that looks like a Warp problem then. I say close it!
