### ISSUE TITLE
ssh integration

### ISSUE THREAD

**Issue by voltrevo** [zed-industries/feedback#168]
**Describe the solution you'd like**

I use ssh a lot, and would love support in zed.

```sh
zed user@host:path/to/workspace
```

And boom, you're coding remotely 😎.

**Describe alternatives you've considered**

vs code went with:

```sh
code --remote ssh-remote+workspace path/to/workspace
```

which is... an odd choice.

**Comment by JosephTLyons** [comment]
Hey @voltrevo, it looks like we have an [issue for remote development](https://github.com/zed-industries/feedback/issues/130).  Would you mind putting a 👍 over on that issue and adding any extra details you are looking for in a comment, so we can keep it in one place?

**Comment by voltrevo** [comment]
Sure thing 👍
