### ISSUE TITLE
Zed CLI Installation Wrong Directory (M1)

### ISSUE THREAD

**Issue by undersquire** [zed-industries/feedback#178]
**Describe the bug**
`Zed > Install CLI` installs the CLI symlink into `/usr/local/bin`, however, for me (M1 Mac) this directory is unused and not added to path by default. [This directory is apparently used by homebrew on *Intel* macs](https://docs.brew.sh/Installation), but the directory `/opt/homebrew/bin` is used instead for M1 (Arm) macs. This means that I have to resort to manually adding `/usr/local/bin` to path in order to use Zed CLI.

Zed should instead install this to a more universal location such as `/usr/bin`, since I believe this is added to path by default on all systems regardless of architecture.

**To reproduce**
Run `Zed > Install CLI` command (or menu option).

**Expected behavior**
Install the symlink into a directory that 

**Environment:**
Zed 0.42.0 – /Applications/Zed.app 
macOS 12.4 
architecture arm64

**Comment by exalted** [comment]
I think everything @undersquire has said is fair. One argument one might make is that `/usr/bin/` is full of "built-in" macOS/*NIX binaries whereas `/usr/local/bin/` might be a "better" choice for all other "3rd-party stuff", such as `zed` in this case.

Also, FWIW, I've tried to run a "clean" Bash on my system with `env -i bash --noprofile --norc` and here's what `echo $PATH` contains:

```
/usr/gnu/bin:/usr/local/bin:/bin:/usr/bin:.
```

I am not 100% sure if this means, on macOS, all `/usr/local/bin` `/bin` and `/usr/bin` are pretty much are expected to be already in your `PATH`.

**Comment by Arden144** [comment]
> Also, FWIW, I've tried to run a "clean" Bash on my system with `env -i bash --noprofile --norc` and here's what `echo $PATH` contains:
> 
> ```
> /usr/gnu/bin:/usr/local/bin:/bin:/usr/bin:.
> ```

macOS uses zsh, not bash, by default which could cause different behavior, but since /usr/local/bin is in /etc/paths, (at least on my M1 running Ventura) it should be safe to use

**Comment by exalted** [comment]
> macOS uses zsh, not bash

Fair enough: Here's `echo $PATH` after a `env -i zsh -d -f -i`:

```
/bin:/usr/bin:/usr/ucb:/usr/local/bin
```

**Comment by exalted** [comment]
So, to summarize, including also contents of `/etc/paths`, these all should be expected to be present in one's PATH, "by default":

```
/usr/local/bin
/usr/bin
/bin
```

And Zed "installing" itself into `/usr/local/bin` seems pretty fair to me.

I am not sure in @undersquire 's setup `/usr/local/bin` isn't there. :/

**Comment by undersquire** [comment]
I ran the installer again and it is working now. I have no idea why it didn't work before when I opened this issue.
