### ISSUE TITLE
Disable Language Server

### ISSUE THREAD

**Issue by bncooney** [zed-industries/feedback#184]
Being able to disable a language server (for example, rust-analyzer) outright would be great. Highlighting, navigation etc.  (provided through tree-sitter as I understand) is enough functionality to make Zed fast and useful.

I appreciate this might be in the pipeline anyway, through future expansion of language server support, but even independently this would be useful settings flag.

Having the language server report warnings that are unrelated to the current state of the buffer, until a file is _saved_, is disorienting. Practically speaking, either you get used to manually waking up the language server (through saving, because the server is inexplicably married to the file system) or you stare at a really slow editor with infinite latency.

None of which matters at all (obviously this is an "issue" between the LSP and how rust-analyzer implements it) if the feature can just be disabled.

**Comment by iamnbutler** [comment]
Try `"enable_language_server": false` in your `settings.json` (more info here: https://zed.dev/docs/configuring-zed)

If that doesn't work, try specifying a language:

```json
"language_overrides": {
  "rust": {
     "enable_language_server": false
  }
}
```

I'm not sure which of these work (I'm OOO right now), but let me know if either or both work. I'll get the docs updated when I have a chance!

**Comment by bncooney** [comment]
That's awesome! Thanks for letting me know.

> I'm not sure which of these work (I'm OOO right now), but let me know if either or both work. I'll get the docs updated when I have a chance!

For rust at least; top-level worked but language override section did not. I'm on 0.42.0.

**Comment by iamnbutler** [comment]
Perfect, thanks! I'll add this to the docs.

**Comment by iamnbutler** [comment]
> That's awesome! Thanks for letting me know.
> 
> > I'm not sure which of these work (I'm OOO right now), but let me know if either or both work. I'll get the docs updated when I have a chance!
> 
> For rust at least; top-level worked but language override section did not. I'm on 0.42.0.

Oh it might be because it should be `Rust` and not `rust`.

**Comment by iamnbutler** [comment]
Just to confirm, you can use this in language overrides if the language keyword is correct. 

Put a PR up for this, should get added to the docs shortly. Going to close this out, let me know if you have any more issues!
