### ISSUE TITLE
Neovim API support for vim users

### ISSUE THREAD

**Issue by tedbyron** [zed-industries/feedback#186]
## Is your feature request related to a problem? Please describe.

Vim support in most editors is often good but not great because there will always be features missing/different behavior from vim emulators

## Describe the solution you'd like

Neovim has an [API](https://neovim.io/doc/user/api.html) which Zed could use for great vim support. This would let Zed avoid trying to emulate all of vim, and non-GUI vim/neovim plugins would still work. There's also a rust crate [neovim-rs](https://docs.rs/nvim-rs/latest/nvim_rs/) for neovim RPC clients, although it looks like development is not too active on it now. 

## Describe alternatives you've considered

- A plugin/extension could probably do this if plugins are supported in the future. VSCode has an extension that does this - [vscode-neovim](https://github.com/vscode-neovim/vscode-neovim)
- An alternative is something like onivim's [libvim](https://github.com/onivim/libvim) - embeddable minimal vim API

**Comment by tedbyron** [comment]
@Kethku definitely fair points, made me change my mind! Hopefully we are able to make some plugins for zed's vim mode in the future, I think that's what bothers me the most about vim emulation stuff is lack of extensibility

**Comment by exalted** [comment]
@Kethku , wow! Congrats to you for this insightful and carefully crafted reply. 👏
