### ISSUE TITLE
Page up / page down keys do not work

### ISSUE THREAD

**Issue by ianthehenry** [zed-industries/feedback#191]
**Describe the bug**

Page up/page down keys don't do what they say on the tin.

**To reproduce**

Press page up/page down. Or, on a laptop keyboard, press fn-up/fn-down.

**Expected behavior**

Pages up or down.

**Environment:**

```
Zed 0.42.0 – /Applications/Zed.app
macOS 12.3.1
architecture x86_64
```

**Comment by Atom-c** [comment]
Also of note/related:

- `home`
- `end`
 
as well do not function.

```
Zed 0.47.1
macOS 12.4
```

**Comment by as-cii** [comment]
This will be fixed with the next release, thanks for the report! 🙏 

@Atom-c: do you mind opening a new issue for `home` and `end` if one doesn't exist already? Thanks!
