### ISSUE TITLE
Code Actions for missing members, better optionals support

### ISSUE THREAD

**Issue by khionu** [zed-industries/feedback#202]
**Is your feature request related to a problem? Please describe.**
When implementing a trait, using the Code Action "Implement Missing Members" should be adaptive to whether the members are optional.

**Describe the solution you'd like**
A dialogue pop up that has all required members checked off, and all the optional ones available for opting into.

**Describe alternatives you've considered**
Since autocomplete for Rust is trait-member aware, maybe skip the dialogue and only do the required members.

**Comment by JosephTLyons** [comment]
Hey @khionu, is this action available in other editors that support Rust development?  I think Zed gets it assists from [rust-analyzer](https://github.com/rust-lang/rust-analyzer), so I don't think Zed has any control over the options provided there, unless there's something extra RA provides that Zed can tap into.

**Comment by JosephTLyons** [comment]
https://rust-analyzer.github.io/manual.html#assists-code-actions

It looks like rust-analyzer only has two actions for adding in trait members:

1. add_impl_default_members
2. add_impl_missing_members

and Zed seems to be showing both:

<img width="298" alt="image" src="https://user-images.githubusercontent.com/19867440/176799821-e15516db-38e7-4018-91b7-31ae3e62daff.png">

I think any other functionality would have to be added to rust-analyzer.

**Comment by khionu** [comment]
What I've described is the behaviour of IntelliJ-Rust as I've experienced it in CLion. I'll proxy this over to the RA team, see if they can accommodate

**Comment by JosephTLyons** [comment]
I'm going to close this one out for now, since it'll be something that needs to happen on RA's end.  If you open up an issue in the RA repo, feel free to post the link here so we can keep up with it.  If RA ends up adding something like this, and it requires changes to Zed to support those new changes, a new issue can be created (or this one can be reopened).
