### ISSUE TITLE
Basic integrated terminal

### ISSUE THREAD

**Issue by fdionisi** [zed-industries/feedback#21]
**Is your feature request related to a problem? Please describe.**
Not having the ability to use an integrated terminal is a game stopper to using Zed daily; switching between multiple windows makes it more likely to lose the coding/thinking flow and _zone out_.

**Describe the solution you'd like**
Even if non-collaborative, a minimal terminal integration would get around this issue.

**Describe alternatives you've considered**
Right now, the only alternative is to switch between applications, which is not ideal.

**Additional context**
I [heard](https://www.youtube.com/watch?v=wXT73bBr83s) that a collaborative-ready integration with the terminal is planned, but it simply feels far timewise – I may be wrong as I don't have much context.

**Comment by paulocoghi** [comment]
I believe a terminal (most probably) can benefit from the same technologies that makes real-time code collaboration possible. It seems reasonable to develop the collaborative terminal on the same root.

**Comment by iamnbutler** [comment]
This one is on the way :) Emphasis on the *basic* for now.

**Comment by iamnbutler** [comment]
You can try this now: 
<img width="575" alt="CleanShot - 2022-07-10 at 13 50 39@2x" src="https://user-images.githubusercontent.com/1714999/178156289-913c09d6-a9fd-49f0-86aa-1506f0a7387e.png">

Technically this is only "soft shipped" (we are still working on it), when it is shipped officially it will be in the release notes!

**Comment by redoxeon** [comment]
As part of the official shipping, will it come with a keyboard shortcut? 😄

**Comment by JosephTLyons** [comment]
> As part of the official shipping, will it come with a keyboard shortcut? 😄

- https://github.com/zed-industries/feedback/issues/259

**Comment by mikayla-maki** [comment]
Added in V0.50
