### ISSUE TITLE
Release notes *could* open by also highlighting the previous version

### ISSUE THREAD

**Issue by exalted** [zed-industries/feedback#211]
I mean, this is seriously a non-issue, but for some weird folk (such as myself 😅 ), after Zed updates itself it could be nice to open the release notes by also highlighting the previous version so that I can scroll through what has changed since then.

**Comment by edwardloveall** [comment]
Agreed! Overall, I'm trying to figure out "Whats changed?" so another helpful thing would be to put the date next to each release.

**Comment by edwardloveall** [comment]
Release notes have a date now. Thank you!

**Comment by exalted** [comment]
Awesome, thanks! That will do it.
