### ISSUE TITLE
Matching pair of open-close symbol highlighting

### ISSUE THREAD

**Issue by mikayla-maki** [zed-industries/feedback#214]
**Is your feature request related to a problem? Please describe.**
When I'm looking at long, rightward drifting code files, it can be difficult to keep track of which context I am in.

**Describe the solution you'd like**
I would like it that if I placed my cursor on or around a `{`, `(`, `[` or `<`, it would highlight the matching pair (and vice versa).

**Describe alternatives you've considered**
Another nice feature that helps with this same problem is adding grey dividers into the indentation to keep track of how many layers deep we are.

**Screenshots**
VS Code does both of the above, as well as highlights the indentation level associated with this block in a lighter gray:

<img width="384" alt="Screen Shot 2022-07-01 at 10 10 46" src="https://user-images.githubusercontent.com/2280405/176940039-6db20219-e7c5-4b73-9d4f-f4ddb0d37d12.png">

**Comment by JosephTLyons** [comment]
This is one I'd really love to see as well

**Comment by JosephTLyons** [comment]
> **Describe alternatives you've considered** Another nice feature that helps with this same problem is adding grey dividers into the indentation to keep track of how many layers deep we are.

Same.  Here's the issue:
-https://github.com/zed-industries/feedback/issues/51
