### ISSUE TITLE
Project panel don't close on cmd+shift+E

### ISSUE THREAD

**Issue by fdionisi** [zed-industries/feedback#223]
**Describe the bug**
Project panel opens but don't close when pressing cmd+shift+E (default toggle).

**To reproduce**
- Manually toggle (close) the project panel
- Hit cmd+shift+E to open
- Hit cmd+shift+E to close

**Expected behavior**
Project panel closes

**Screenshots**

https://user-images.githubusercontent.com/8927326/177505730-459746de-6e1d-4ec8-8969-f6b2a98bacf8.mp4

> **Note** I can assure I'm hitting cmd+shift+E multiple times, but apparently, Kap's key-cast plugin has issues w/ multiple monitors, and I'm too lazy right now.

**Environment:**
Copy & paste output of this command:
```sh
Zed 0.44.0 – /Applications/Zed.app
macOS 12.1
architecture arm64
```

**Comment by JosephTLyons** [comment]
Hey @fdionisi.

Zed has two similar types of commands for either panel:

For the Project Panel:

- "cmd-shift-E": "project_panel::Toggle",
- "cmd-b": "workspace::ToggleLeftSidebar",

For the Contacts Panel:

- "cmd-shift-C": "contacts_panel::Toggle",
- "cmd-shift-B": "workspace::ToggleRightSidebar"

The first command, in either of those groups, is used to move the user's focus to that panel.  If you want to interact with the Project Panel, you can use `cmd-shift-E` to move the focus to that panel (which will allow you to interact with this panel via the keyboard).  These commands have the byproduct of also opening the panel if it is closed.  If the panel is already open, nothing happens after the focus is moved.

The second command, in either group, is used to toggle either panel's open / close state.

**Comment by fdionisi** [comment]
Thank you @JosephTLyons for the explanation. Indeed, using cmd-b works as expected.

With the term "_toggle_" I was supposing the action implied by the name, rather than "_focus_".
Am I pedantic if I suggest changing "project_panel::Toggle" and "contacts_panel::Toggle" to "*::Focus"?

**Comment by JosephTLyons** [comment]
> Thank you @JosephTLyons for the explanation. Indeed, using cmd-b works as expected.
> 
> With the term "_toggle_" I was supposing the action implied by the name, rather than "_focus_". Am I pedantic if I suggest changing "project_panel::Toggle" and "contacts_panel::Toggle" to "*::Focus"?

@maxbrunsfeld

**Comment by maxbrunsfeld** [comment]
You’re absolutely right @fdionisi; we should rename it.

**Comment by aexvir** [comment]
I was also just hitting this and I also think that `toggle` is misleading; `focus` makes much more sense

**Comment by as-cii** [comment]
The renamed commands will be included in the next release, thanks for the reports!
