### ISSUE TITLE
Ability to highlight and copy text from terminal in zed

### ISSUE THREAD

**Issue by kevinamstutz** [zed-industries/feedback#230]
**Is your feature request related to a problem? Please describe.**
When using the terminal from inside zed, I'm unable to highlight/copy text from the terminal.

**Describe the solution you'd like**
The ability to highlight/copy text from the terminal from within zed.

**Describe alternatives you've considered**
I can just pop an external terminal, no problem.

**Comment by maxbrunsfeld** [comment]
Thanks for the feedback 😁.  We weren't planning on telling people about the terminal while it's still in development, but I'm impressed that you discovered it!

**Comment by kevinamstutz** [comment]
I found it on accident and thought I missed the announcement -- it works pretty well considering it is still in development! Keep up the awesome work!

**Comment by mikayla-maki** [comment]
Fixed in next release
