### ISSUE TITLE
cli - can't open file not created yet

### ISSUE THREAD

**Issue by ksandvik** [zed-industries/feedback#233]
**Before you begin**
Check the backlog of issues to reduce the chances of creating duplicates; if an issue already exists, place a `+1` (👍) on it.

**Describe the bug**
zed command line does not create a file that does not exist.

**To reproduce**
$ zed /tmp/foo.go

**Expected behavior**
Zed editor opens up with the file in the window.
[Zed.log](https://github.com/zed-industries/feedback/files/9057783/Zed.log)

** Actual result **
13:15|ksandvik@C02T26J4GTF1| ~> zed ~/tmp/foo.go
Error: No such file or directory (os error 2)
/Users/ksandvik

**Screenshots**

**Environment:**
Copy & paste output of this command:
```sh
echo $(/Applications/Zed.app/Contents/MacOS/cli --version) "\n"macOS $(sw_vers -productVersion) "\n"architecture $(uname -m)
```
Zed 0.45.0 – /Applications/Zed.app \nmacOS 12.4 \narchitecture x86_64

*If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.*

**Comment by ksandvik** [comment]
[Zed.log](https://github.com/zed-industries/feedback/files/9057786/Zed.log)

**Comment by JosephTLyons** [comment]
Hey @ksandvik, is this a feature that other editor CLIs have?  Just curious if it exists out in the wild or if its a new thing you'd just like to see in Zed.

**Comment by yoroshikun** [comment]
You can do this with vscode iirc (code hello_world.rs) will open the editor with hello_world.rs created and opened

**Comment by chenzhekl** [comment]
That functionality is standard for most editors. For example, `vim foo.py` will open a new buffer. Any subsequent saves (`:w`) will create `foo.py` if the file does not exist and write the content to it.

**Comment by hovsater** [comment]
I was very surprised when Zed refused to open a non-existent file. Pretty much every editor out there supports this feature. Usually by creating an unsaved named buffer where the name is whatever you provided when invoking the binary.

**Comment by mikayla-maki** [comment]
A first pass at this should go out in a release or two :)
