### ISSUE TITLE
Elixir support

### ISSUE THREAD

**Issue by 4141done** [zed-industries/feedback#235]
**Describe the solution you'd like**
Created this as a generally place for people to add 👍  for Elixir support.

Personally I'd like to have code highlighting work for Elixir/Elixir-adjacent formats (`.eex`, `.ex`, `.exs`, `.heex`). I don't have much need for a language server.

**Describe alternatives you've considered**
New to zed but I couldn't find any option to set syntax.  My current workaround is to use another editor.

**Comment by hovsater** [comment]
Can this issue be closed given there's Elixir support in Zed now?

**Comment by mikayla-maki** [comment]
Looks like it!

**Comment by Defman21** [comment]
Does “support” not include LSP?

**Comment by hovsater** [comment]
> Does “support” not include LSP?

Zed ships with LSP support for Elixir.

**Comment by Defman21** [comment]
For some reason it's not working for me, I'm going to open a new issue then.

**Comment by Defman21** [comment]
Nevermind, opening zed from the CLI makes it working. Should I report it that it does not work otherwise (opening from Launchpad?)

**Comment by benonymus** [comment]
While the elixir support is working well, would it be possible to expand the support to .eex and .heex file types as well? 
The formatter is the same, not sure about the highlighting.
