### ISSUE TITLE
Language Servers are not connected/working

### ISSUE THREAD

**Issue by logo4poop** [zed-industries/feedback#237]
**Describe the bug**
The C++ and Rust language servers (clangd, rust-analyzer) are seemingly not connecting to Zed, I have not tried any other language server, but I assume the problem is consistent throughout. All language-specific features outside of syntax highlighting do not work, the problems tab reports that there are no problems even if there should be some listed.
**To reproduce**
Unsure, this happened out of nowhere however everything used to work.
**Expected behavior**
Anything which should be reported such as errors or types should be shown.

**Environment:**
Copy & paste output of this command:
```sh
echo $(/Applications/Zed.app/Contents/MacOS/cli --version) "\n"macOS $(sw_vers -productVersion) "\n"architecture $(uname -m)
```
Zed 0.45.0 – /Applications/Zed.app
macOS 11.3.1
architecture x86_64

*If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.*
[Zed.log](https://github.com/zed-industries/feedback/files/9058088/Zed.log)

**Comment by as-cii** [comment]
Hey @logo4poop, thanks for the feedback! Is this still an issue? It should work out of the box and I am surprised to not see any error in the logs. 

Could you try opening a Rust or C++ project with the following incantation:

```bash
RUST_LOG=lsp=trace /Applications/Zed.app/Contents/MacOS/zed /path/to/your/project
```

And pasting here the contents of `stdout` after opening a Rust or C++ file? This will give the LSP a chance to start and we should see why the language server isn't working for you.

**Comment by logo4poop** [comment]
Hey, thanks for responding. It seems to have magically fixed itself, I am still curious on why it wasn't working though. I'll close this issue for now, but if anyone has a similar problem I suppose we could reopen it.

**Comment by tokisakiyuu** [comment]
I had the same problem.

#### Environment
```bash
> echo $(/Applications/Zed.app/Contents/MacOS/cli --version) "\n"macOS $(sw_vers -productVersion) "\n"architecture $(uname -m)
Zed 0.77.3 – /Applications/Zed.app 
macOS 13.1 
architecture x86_64
```
```bash
> rustup component list --installed
cargo-x86_64-apple-darwin
clippy-x86_64-apple-darwin
rls-x86_64-apple-darwin
rust-analysis-x86_64-apple-darwin
rust-docs-x86_64-apple-darwin
rust-src
rust-std-wasm32-unknown-unknown
rust-std-x86_64-apple-darwin
rust-std-x86_64-unknown-linux-musl
rustc-x86_64-apple-darwin
rustfmt-x86_64-apple-darwin
```

#### Log File
[Zed.log](https://github.com/zed-industries/community/files/11007681/Zed.log)
