### ISSUE TITLE
Make it clear in the docs that diagnostics/RA only works on cargo-based projects.

### ISSUE THREAD

**Issue by iamnbutler** [zed-industries/feedback#24]
Make it clear in the docs that diagnostics/RA only works on cargo-based projects. Rust analyzer only works out of the box on cargo-based projects. This is a RA thing, but might be worth calling out for people just exploring Rust to test out Zed.

**Comment by JosephTLyons** [comment]
Should we keep this issue around?  I imagine the Zed documentation probably won't take on covering issues within language servers, especially once it is possible to pick and choose which language server one wants to use with Zed.

**Comment by iamnbutler** [comment]
Yep, I'm just going to close this.
