### ISSUE TITLE
0.45.0 crash on my OS X 10.14.6

### ISSUE THREAD

**Issue by rhapsodyn** [zed-industries/feedback#256]
Start the app with an instant crash.

[crash.log](https://github.com/zed-industries/feedback/files/9068138/crash.log)

**Comment by mikayla-maki** [comment]
Seems to be the same bug as this one: https://github.com/zed-industries/feedback/issues/201

**Comment by mikayla-maki** [comment]
Max has a potential workaround here: https://github.com/zed-industries/feedback/issues/201#issuecomment-1174514326
