### ISSUE TITLE
When I save a file that contains (only?) macros, the file is saved empty

### ISSUE THREAD

**Issue by russelldb** [zed-industries/feedback#258]
**Describe the bug**
I open a file called `macros.rs`. I know the file is "fine" as cargo check and cargo compile all work. And I use these macros in my code. HOWEVER, once I open this file, diagnostics reports these errors:

```
no btreemap in diffawmap::macros
```

and

```
import resolution is stuck, try simplifying macro imports
```

Which may be the cause of what happens next. If I hit `cmd-s` to save the file, all its contents are removed. I made (and attach) a video. 

**To reproduce**
Open a file with a macro def and maybe a re-export like

```
pub use ::maplit::btreemap;
```

Then save it

**Expected behavior**
I expected to be able to edit the file and save it without losing its contents

**Screenshots**

https://user-images.githubusercontent.com/56321/178004207-f1ce1080-301e-45cb-8195-2b4f7feb8a61.mov

**Environment:**
`Zed 0.45.0 – /Applications/Zed.app \nmacOS 12.4 \narchitecture x86_64`

*If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.*
[Zed.log](https://github.com/zed-industries/feedback/files/9072533/Zed.log)

**Comment by as-cii** [comment]
Alternatively, can you try opening Zed with the following bash incantation?

```bash
RUST_LOG=lsp=trace /Applications/Zed.app/Contents/MacOS/zed your-project-path
```

And then try to reproduce the problem as you did in the video? This will print out tracing information about the LSP to stdout: pasting the contents of those tracing logs here should tell us what rust-analyzer is instructing Zed to do.

**Comment by russelldb** [comment]
[lsp.log](https://github.com/zed-industries/feedback/files/9072796/lsp.log)

Oh wow, VSCode does it too!

Emacs (also using rust analyzer) does not do it, but something weird happens because LSP disconnects and reconnects

**Comment by russelldb** [comment]
If it would still help to set up a minimum-failing-micro-repo I can try this weekend, I'm about to defenestrate my laptop and call it a week

**Comment by as-cii** [comment]
Hahaha 💻➡️🪟 

Thanks so much for posting that log! I am not sure we can do much here because we blindly do what rust-analyzer tells us when formatting, and indeed they're telling us to clear the file. 😢 Given that you can reproduce with VS Code, I think our best bet is to report this issue to them and I believe it would help them a lot to checkout a repo where this issue reproduces cleanly.

One last question: what happens if you format the file using `cargo fmt --package name-of-package-containing-macro`?

**Comment by russelldb** [comment]
> One last question: what happens if you format the file using cargo fmt --package name-of-package-containing-macro?
Nothing afaict.

Feel free to close, thanks.
