### ISSUE TITLE
Key command to deploy terminal

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/feedback#259]
Since the secret has been let out that Zed now has a Terminal, I think a key combo could probably be added.  I've been using it enough and think it's in a stable enough place to expose that sort of access.

**Comment by rkusa** [comment]
Until it is provided by default, I had success adding it myself by putting the following into my `keymap.json`:

```json
[
  {
    "context": "Editor",
    "bindings": {
      "ctrl-escape": "terminal::DeployModal"
    }
  },
  {
    "context": "ModalTerminal",
    "bindings": {
      "escape": "terminal::DeployModal"
    }
  }
]
```

This opens the modal via `CTRL+Escape`, and closes it via a simple `Esc` press. There is also `terminal::Deploy` if you want a terminal tab instead.

**Comment by mikayla-maki** [comment]
The command for now is ctrl-`, because VSCode's shift-ctrl-` is impossible to type. This is open to change. 

btw @rkusa `terminal::Deploy` has been changed to `workspace::NewTerminal` :)
