### ISSUE TITLE
Setting for default directory when deploying terminal

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/feedback#262]
**Is your feature request related to a problem? Please describe.**
I think it would be nice to have a setting for the default directory to deploy the terminal in.

**Describe the solution you'd like**
I think there could be at least 2 options:

1. A way for the user to put in a hardcoded path, maybe they want to always use their home directory
2. Something to indicate to use this project's root path

**Comment by mikayla-maki** [comment]
As of 0.46 the default behavior is to grab your currently open file's project root (you can have multiple folders open in a project), or default to the home directory if the current root doesn't work for some reason. Hardcoded path is a good idea too 👀

**Comment by mikayla-maki** [comment]
This, and several other configuration options, are coming the next release.
