### ISSUE TITLE
Give more context to breadcrumbs when in 3rd party libraries

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/feedback#264]
**Is your feature request related to a problem? Please describe.**
When clicking around into 3rd party crates, it's easy to forget where you are at, because the breadcrumbs don't give enough context of where you are.

**Describe the solution you'd like**
Display more of the path leading up the filename

**Screenshots**
In this screenshot, I am looking at `serde`'s `Deserialize` trait.

Breadcrumbs in Zed

<img width="262" alt="image" src="https://user-images.githubusercontent.com/19867440/178092644-81d995ec-b4cd-4e91-867c-7a58bd8d0ce1.png">

Breadcrumbs in VS Code

<img width="848" alt="image" src="https://user-images.githubusercontent.com/19867440/178092655-de71565f-7619-4b8b-9380-bd608eb736b2.png">

Most Rust devs know where the Deserialize trait comes from, but I there are times when one might get confused where they are when command-clicking around into lesser-known libs.

An additional issue I noticed was that when I searched for code inside of the lib, the Project Search has "untitled" for the excerpt header:

<img width="884" alt="image" src="https://user-images.githubusercontent.com/19867440/178092736-7642a27a-1aea-4be8-8729-c6a367a71e03.png">

**Comment by aexvir** [comment]
as feedback to this: while I agree that getting more information on the breadcrumbs would be nice, please don't make it like vscode, or if that's how the implementation is going to be, put it behind some option so it can be turned off and go back to the current breadcrumb

the breadcrumb in vscode has so much useless (imo) information; of course the package is on that directory, where all the other packages are, I don't need to see that information, it's just visual clutter and it's distracting

as suggestion I'd say that some intelligent "package aware" breadcrumbs would be the nicest solution, so all the "noise" like where the package is installed can be skipped and it just shows paths relative to the package itself, something like

> 🐭 [encoding/json > decode.go > Unmarshal](https://pkg.go.dev/encoding/json#Unmarshal)

for go packages or 
> 🦀 [serde > mod.rs > pub trait Deserialize](https://docs.serde.rs/serde/de/trait.Deserialize.html)

for rust

...at least that's more than enough information for me; of course other people might disagree and would prefer the full path but I think that as long as it's behind an option it should be ok to have more than one "breadcrumb style"

wdyt?

**Comment by JosephTLyons** [comment]
> as feedback to this: while I agree that getting more information on the breadcrumbs would be nice, please don't make it like vscode, or if that's how the implementation is going to be, put it behind some option so it can be turned off and go back to the current breadcrumbs
> 
> the breadcrumbs in vscode have so much useless (imo) information; of course the package is on that directory, where all the other packages are, I don't need to see that information, it's just visual clutter and it's distracting
> 
> as suggestion I'd say that some intelligent "package aware" breadcrumbs would be the nicest solution, so all the "noise" like where the package is installed can be skipped and it just shows paths relative to the package itself, something like
> 
> > 🐭 [encoding/json > decode.go > func Unmarshal](https://pkg.go.dev/encoding/json#Unmarshal)
> 
> for go packages or
> 
> > 🦀 [serde > mod.rs > pub trait Deserialize](https://docs.serde.rs/serde/de/trait.Deserialize.html)
> 
> for rust
> 
> ...at least that's more than enough information for me; of course other people might disagree and would prefer the full path but I think that as long as it's behind an option it should be ok to have more than one "breadcrumb style"
> 
> wdyt?

Yes, I agree.  VS Code's has too much information, something in between not enough information and too much information would be ideal.

**Comment by mikayla-maki** [comment]
This should be fixed in the next release. Right now we just show the full path, but may eventually do something more package aware.
