### ISSUE TITLE
Zed does not output the tab character 

### ISSUE THREAD

**Issue by loudermachine** [zed-industries/feedback#273]
**Describe the bug**
With the settings as `hard_tabs: true`, Zed still does not output the tab character, writing a soft tab with spaces. This makes it really hard to write Makefiles with Zed.  

**To reproduce**
- Set `hard_tabs: true` on settings.json
- Create a file `test.txt`, press tab and save it
- Run `/bin/cat -e -t -v test.txt` to show non-printing characters. The file will have spaces instead of `^I`, which represents the tab character. 

Another way to test it is to create a Makefile with a simple recipe and run `make`, a `missing separator` error should occur.

**Expected behavior**
Zed should output a tab character

**Comment by maxbrunsfeld** [comment]
Thanks for the report @loudermachine.

**Comment by Grant-Giesbrecht** [comment]
I'm still encountering this problem with v0.68.1. I've set hard tabs to true, but Zed still inserts spaces instead of a tab character.

**Comment by ForLoveOfCats** [comment]
Can you verify that your `settings.json` does not contain any syntax errors?

**Comment by Grant-Giesbrecht** [comment]
I don't see any syntax errors. My `settings.json` just has:
```
{
    "theme": "One Dark",
    "buffer_font_size": 15,
    "hard_tabs": true
}
```
