### ISSUE TITLE
System-wide macOS keyboard shortcuts don't work

### ISSUE THREAD

**Issue by adamsoutar** [zed-industries/feedback#277]
**Describe the bug**

There are some keyboard shortcuts that are near-universal in macOS which users may expect to work in Zed, too. For example, they are implemented in other text editors and IDEs.

I previously raised issue #143 , but am closing it in favour of a list since I've noticed a few 😅 

 - `Ctrl+Cmd+F` doesn't fullscreen the window
 - `Ctrl+Cmd+Space` doesn't open the emoji picker
 - `Cmd+M` doesn't minimise the window to the dock
 - `Cmd+H` doesn't hide Zed.

**Expected behavior**

Hit these keyboard shortcuts in other apps like Finder, Safari, Atom, VS Code.

**Comment by alevroub** [comment]
Another very important one (for me) is moving focus to the next window (System preferences > Keyboard > Shortcuts).

**Comment by as-cii** [comment]
Thank you both for the feedback!

@alevroub: moving focus to the next window should work. Are you on v0.49.1? We had a bug in v0.49.0 that prevented that shortcut from working. I'd love if you could give it another try and see if it works for you now. Thanks!

**Comment by alevroub** [comment]
@as-cii It works as of `v0.49.1`!

**Comment by as-cii** [comment]
All the remaining menu items will be included in the next release, thanks so much for the report!

**Comment by stjepangolemac** [comment]
I'm running the 0.50 release now and the fullscreenshortcut doesn't work. The Cmd+H one works though.

**Comment by mikayla-maki** [comment]
We use `fn-f` for full screen!

**Comment by stjepangolemac** [comment]
Oh that works. I don't think I've seen the usage of `fn-f` before, why do we use that?

**Comment by mikayla-maki** [comment]
Probably because `shift-cmd-f` opens the project search. I actually can't find a way to rebind that, surprisingly.

**Comment by stjepangolemac** [comment]
But I believe `ctrl-cmd-f` is the one for fullscreen, not `shift-cmd-f`?

**Comment by mikayla-maki** [comment]
Oh yeah, you're right. I'll see about changing that then :)

**Comment by as-cii** [comment]
> But I believe `ctrl-cmd-f` is the one for fullscreen, not `shift-cmd-f`?

This will be included in the next release, thanks for the report! 🙏
