### ISSUE TITLE
Persist folders added to project (save workspace)

### ISSUE THREAD

**Issue by redoxeon** [zed-industries/feedback#290]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to open multiple folders in a single project or workspace without having to add individual folders every time I open Zed.

**Describe the solution you'd like**
Something similar to VS Code's "Save workspace" feature where you can have a set of folders (and potentially settings) saved as a workspace/project.

**Describe alternatives you've considered**
Current alternatives involve opening one folder, then the others in succession through "add folder to project" or to put all project folders in a "super-folder" that can just have all sub-projects in it.

**Comment by mikayla-maki** [comment]
Blocks on: https://github.com/zed-industries/feedback/issues/430

**Comment by mikayla-maki** [comment]
This should ship in a few releases
