### ISSUE TITLE
Zed uses 400%+ CPU with possible memory leak

### ISSUE THREAD

**Issue by snadon** [zed-industries/feedback#300]
**Describe the bug**
When I open a lucky framework project, the CPU usage goes up to 400%+ and memory keeps growing.

**To reproduce**
Have a lucky framework project with files under the `lib/` folder. When I `rm -rf lib/*` the problem goes away. When I remove the project folder, the CPU goes down but the memory seems to stay high.

**Expected behavior**
CPU and memory usage shouldn't get out of control.

**Environment:**
```
Zed 0.47.1 – /Applications/Zed.app 
macOS 13.0 
architecture arm64
```
![Screenshot 2022-07-14 at 11 44 50 AM](https://user-images.githubusercontent.com/539572/179023499-8d692233-e836-41e5-93b7-48fd5c59d141.png)

**Comment by as-cii** [comment]
Hey @snadon, thanks so much for the feedback! Does this happen on all lucky framework projects? We'd love to look into this post-haste and so it would help us immensely if you could point us to a repository that we can clone to observe the problem.

Alternatively, do you have some reproduction steps we can follow to reproduce the problem?

Thanks! 🙏

**Comment by snadon** [comment]
Of course, you can clone the lucky framework website:
```
git clone git@github.com:luckyframework/website.git
script/setup
```
Add the project folder `website` in Zed and watch.

**Comment by maxbrunsfeld** [comment]
Thanks for the details @snadon. I can reproduce the problem now.

**Comment by as-cii** [comment]
A fix for this will be released with the next version, thanks so much for the detailed report!

**Comment by maxbrunsfeld** [comment]
Zed v0.48 is out, and has a fix for this. @snadon Please let us know if you hit any other issues like this.
