### ISSUE TITLE
Can't search when in Vim normal mode

### ISSUE THREAD

**Issue by Awjin** [zed-industries/feedback#302]
**Before you begin**

Done.

**Describe the bug**

If I start a search while vim is in normal (not insert) mode, the search text can't be edited.

*Note: If I start the search, click in the file, then click back into the searchbox, I can then edit the search text.*

**To reproduce**

- Enable `vim_mode`
- Open a file without enabling vim's insert mode
- Cmd-f
- Try typing in the searchbox

**Expected behavior**

- I can edit the search text no matter the vim mode

**Screenshots**

N/A

**Environment:**

```sh
Zed 0.47.1 – /Applications/Zed.app
macOS 12.4
architecture x86_64
```

**Comment by Kethku** [comment]
I can't repro. The cursor is sent to the search box and is in visual mode. You can then hit c to change the contents of the box.

There is still some design work around whether having vim modes in these single line editors is worth it. For now we are doing the maximally powerful thing and then walking it back if it is too painful

**Comment by Awjin** [comment]
IMO it's very surprising behavior that the searchbox itself has a visual mode. I would expect the search to behave like vim's `/`.

**Comment by Kethku** [comment]
Its less an intentional decision in this case than a consequence of vim mode being available in all of the editors. It is something we will iterate on

**Comment by Awjin** [comment]
Got it. Thanks for the quick response!

**Comment by Starblade42** [comment]
For what it's worth, I was still thinking "VIM!!" when I got into the single line editor, but was confused that the word under my cursor at the time was transported into the single line editor. I was invoking search using "/" so that partly has to do with it.

**Comment by Kethku** [comment]
Let me know if you have any feedback. I'm still on the fence for whether vim mode in single line editors is useful or not.

**Comment by logo4poop** [comment]
I don't really find it useful, even Vim doesn't do that itself. It might be something that is more important on a case by case basis though.

**Comment by Kethku** [comment]
This makes good sense to me for the search box. Would a version which has the text selected (as though vim mode were disabled) but was functionally like insert mode be better? This way you get the pre-rendered text, but can press escape twice to swap to vim mode.

The issue I have in mind is one in vim today. Editing a long search is very painful. Similarly editing commands in command mode is frustrating because you only have access to insert mode style bindings (baring some workarounds). My hope is to get to some best of both worlds without that drawback

It may be that such a thing would be too different though...

**Comment by Awjin** [comment]
Fair enough, and I agree that exploring is good.

> Yes small text edits are the norm, but longer searches aren't that rare, and this isn't just about searches. It's about query boxes such as the outline view, the command palette, the rename editor, file renames, etc

> Many of those are small text contexts, but not always. Its also worth pointing out that those contexts might benefit from enabling macros once they are implemented which could be pretty useful for applying a complex rename or similar.

Maybe there is a dichotomy here. For me, cmd+F is almost always a means to an end; a way to find what I'm looking for in the code, as fast as possible, so I can maintain a mental model of the code I'm working with. Any UX friction risks breaking flow.

Whereas the other cases you mention (even "search all files" feels different from cmd+F) might benefit from having vim modes.

**Comment by Kethku** [comment]
Yeah I'm very confident that an option for this would be required in any case
