### ISSUE TITLE
format_on_save with prettier

### ISSUE THREAD

**Issue by rvanmil** [zed-industries/feedback#309]
I'm trying to use prettier as external `format_on_save` command. It appears though that prettier needs to be called with the filename (https://prettier.io/docs/en/cli.html#--stdin-filepath) when passing the text on stdin. For example, this will not work:

`cat abc.ts | prettier`

It will fail with the error "No parser and no file path given, couldn't infer a parser."

To make this work prettier must be called like this:

`cat abc.ts | prettier --stdin-filepath abc.ts`

So I guess to make this work with `format_on_save` I'll need to be able to access the current filename and pass it as and argument. I imagine it would like somewhat like this in the settings.json file:

```
"format_on_save": {
    "external": {
        "command": "./node_modules/.bin/prettier",
        "arguments": [
           	"--stdin-filepath",
           	"$filename"
        ]
    }
}
```

I was able to simulate this and it work properly if I hardcode the filename which I am testing with, for example when editing the file `src/db.ts` Zed will properly format the file with prettier when I use this config:

```
"format_on_save": {
    "external": {
        "command": "./node_modules/.bin/prettier",
        "arguments": [
           	"--stdin-filepath",
           	"src/db.ts"
        ]
    }
}
```

As a side-effect, using this configuration will let Zed format any `.ts` file properly, I guess because it determines which parser to use on stdin by examining the file specified with the `--stdin-filepath` argument 😊

**Comment by as-cii** [comment]
Hey @rvanmil, thanks for the feedback! We support interpolation of the saved buffer path via a special `{buffer_path}` string. You should be able to invoke prettier as described in the [JavaScript](https://zed.dev/docs/javascript) guide of Zed's docs:

```json
"format_on_save": {
    "external": {
        "command": "./node_modules/.bin/prettier",
        "arguments": [
           	"--stdin-filepath",
           	"{buffer_path}"
        ]
    }
}
```

I am going to close this for now, but please feel free to re-open if I missed something!

**Comment by rvanmil** [comment]
Thanks, and sorry! I completely missed that part of the documentation.

**Comment by as-cii** [comment]
No worries whatsoever: I appreciate you were able to figure out a workaround in the meantime and that you spent time reporting an issue! 🙏

We are still iterating on our docs and we probably could do a better job hinting at this feature in the editor itself. I am going to work right now on adding a comment to the default `settings.json` (that you can open via the command palette or the application menu) that illustrates this feature.

**Comment by formbench-tech** [comment]
does it respect the .prettierrc file or do we have to tell it where to find it?
