### ISSUE TITLE
allow chosing different font (and font size) for terminal buffers

### ISSUE THREAD

**Issue by aexvir** [zed-industries/feedback#312]
**describe the solution you'd like**
I have fancy prompts and clis that leverage nerdfonts for looking pretty 😆 
yeah... first world problems... but it would be really nice to be able to set up a different font and size so the custom characters show correctly

bonus points for allowing different fonts for ascii and non-ascii characters like iterm does 

**screenshots**
alacritty with fira code nerd font
<img width="1322" alt="Screenshot 2022-07-14 at 22 29 16" src="https://user-images.githubusercontent.com/8055505/179077440-0bda06f2-1599-4333-9c76-6c1650d8b8c4.png">

iterm with different ascii and non-ascii font (fira code & fira code nf)
<img width="1055" alt="Screenshot 2022-07-14 at 22 30 17" src="https://user-images.githubusercontent.com/8055505/179077592-e656e0cf-bf5d-4d90-96ec-01d6c5bf6ad0.png">

zed 😅 
<img width="1552" alt="Screenshot 2022-07-14 at 22 17 57" src="https://user-images.githubusercontent.com/8055505/179077772-478223c6-d043-407a-b149-baf5da8d4409.png">

**Comment by mikayla-maki** [comment]
Would you mind dropping your shell and configuration settings / fonts? So I can install it and work through the issues.

**Comment by JosephTLyons** [comment]
Also, whatever you are using for the custom prompt :)

**Comment by aexvir** [comment]
sure, I think that the easiest thing to test would be the prompt
I use [oh my posh](https://ohmyposh.dev) with the following config

<details>
<summary>Details</summary>

```json
{
  "$schema": "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json",
  "blocks": [
    {
      "alignment": "left",
      "segments": [
        {
          "background": "black",
          "foreground": "blue",
          "leading_diamond": "\ue0b6",
          "properties": {
            "folder_icon": "\uf069",
            "folder_separator_icon": "<lightBlue>\uf460</>",
            "home_icon": "\uf7dd",
            "mapped_locations": {
              "~/.config": "\uf085",
              "~/.ssh": "\uf43d",
              "~/books": "\uf02d",
              "~/documents": "\uf0b1",
              "~/downloads": "\uf0ed",
              "~/go": "\ue627",
              "~/google drive": "\uf7b5",
              "~/projects": "\ue795"
            },
            "style": "agnoster_short"
          },
          "style": "diamond",
          "template": "{{ .Path }} <red>\uf054</><yellow>\uf054</><green>\uf054</>",
          "trailing_diamond": "\ue0b0 ",
          "type": "path"
        }
      ],
      "type": "prompt"
    },
    {
      "alignment": "right",
      "segments": [
        {
          "foreground": "#ffffff",
          "properties": {
            "command": "printf (direnv prompt)",
            "shell": "fish"
          },
          "style": "plain",
          "type": "command"
        },
        {
          "foreground": "#6ca35e",
          "style": "plain",
          "template": " \uf898 {{ if .PackageManagerIcon }}{{ .PackageManagerIcon }} {{ end }}{{ .Full }}",
          "type": "node"
        },
        {
          "foreground": "#306998",
          "properties": {
            "display_default": false,
            "display_error": false,
            "display_mode": "files",
            "fetch_virtual_env": false
          },
          "style": "plain",
          "template": " \ue606 {{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }} {{ end }}{{ .Full }}{{ end }}",
          "type": "python"
        },
        {
          "foreground": "#7fd5ea",
          "style": "plain",
          "template": " \ue627 {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}",
          "type": "go"
        },
        {
          "foreground": "#99908a",
          "style": "plain",
          "template": " \ue7a8 {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}",
          "type": "rust"
        },
        {
          "background": "black",
          "foreground": "lightWhite",
          "leading_diamond": " \ue0b6",
          "properties": {
            "branch_icon": "\uf418 ",
            "fetch_status": false
          },
          "style": "diamond",
          "template": "{{ .HEAD }} {{ .BranchStatus }}{{ if .Working.Changed }} \uf044 {{ .Working.String }}{{ end }}{{ if and (.Staging.Changed) (.Working.Changed) }} |{{ end }}{{ if .Staging.Changed }} \uf046 {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0}} \uf692 {{ .StashCount }}{{ end }}{{ if gt .WorktreeCount 0}} \uf1bb {{ .WorktreeCount }}{{ end }}",
          "trailing_diamond": "\ue0b4",
          "type": "git"
        },
        {
          "background": "black",
          "foreground": "white",
          "leading_diamond": " \ue0b6",
          "properties": {
            "style": "austin",
            "threshold": 500
          },
          "style": "diamond",
          "template": "{{ .FormattedMs }}",
          "trailing_diamond": "\ue0b4",
          "type": "executiontime"
        },
        {
          "foreground": "green",
          "foreground_templates": [
            "{{ if gt .Code 0 }}red{{ end }}"
          ],
          "properties": {
            "always_enabled": true
          },
          "style": "plain",
          "template": " {{ if gt .Code 0 }}\uf06a{{else}}\uf058{{ end }} ",
          "type": "exit"
        }
      ],
      "type": "rprompt"
    }
  ],
  "version": 2
}
```

</details>

it should work on any shell; on `fish` you can enable the prompt by adding
```fish
oh-my-posh --init --shell fish --config /wherever/you/saved/that.json | source
```

**Comment by aexvir** [comment]
and the fonts are fira code and fira code nerd font
which you can get from homebrew by running
```shell
brew tap "homebrew/cask-fonts"
brew install font-fira-code font-fira-code-nerd-font
```

**Comment by jansol** [comment]
If I read OP correctly what this is really about is a proper font fallback mechanism.

I.e. if the chosen font does not provide a given glyph, look through a (list of) other font(s) until one is found that contains the required glyph. Either with a list configured within zed or one provided by the OS.

**Comment by aexvir** [comment]
hmm... I can't say for sure as I don't know very well the implementation details; but I don't think so
fira code nerd font has both ascii and non-ascii characters included, hence the request of allowing a different font for the terminal buffer

the motivation for a setting allowing different fonts on ascii and non-ascii characters comes mainly from the fact that some of the non-ascii characters don't look good at the same size as the text, at least that's what happens in iterm, but this might not be needed at all if the rendering is good I think

on alacritty I only use fira code nerd font with a single size and it all looks nice

**Comment by mikayla-maki** [comment]
Yeah, this is a major item on the todo list! Right now I just use whatever the Zed font is and don't think about it. Adding settings and a fallback mechanism are essential before I consider this 'released'.

**Comment by aexvir** [comment]
but why font fallback? 🤔 
I don't think the editor should try multiple fonts when rendering text
if the font includes the characters then they should be displayed and otherwise it will look like it does now

if I just use the current `buffer_font_family` setting for setting the font to "FiraCode Nerd Font" it already looks ok
the only thing needed is allow the terminal buffer to use a different font from the other buffers

or am I missing something? 😅 
<img width="1552" alt="Screenshot 2022-07-14 at 23 26 25" src="https://user-images.githubusercontent.com/8055505/179089180-1c472980-da31-4fbd-b508-20e3d87f7228.png">

**Comment by aexvir** [comment]
or you mean fallback as in "if terminal_buffer_font_family is not set then use buffer_font_family"?

**Comment by mikayla-maki** [comment]
More that I haven't put any thought or effort into terminal settings, terminal fonts, and the intricacies thereof. It's on the list though! I'll do something, probably in the next week or two :D

**Comment by aexvir** [comment]
that's fine, this is not a critical feature by any means, I just didn't understand the glyph fallback mechanism and why is needed 😄️

**Comment by jansol** [comment]
Font fallback would solve the problem illustrated in OP, and also another much bigger one, which is that there exist only a couple of fonts that get anywhere near covering even most popular modern-day languages.

For example ruby happens to be a rather popular language in Japan but much less used elsewhere. As a result a nontrivial portion of the ruby code out in the wild has its comments written in Japanese. It would be unconvenient to be forced to use something like [unifont](https://unifoundry.com/unifont/index.html) as the sole font for my terminal and text editor just to be able to read the code comments (and lose goodies like nerd font symbols in the process).

What iTerm does is it checks of a glyph is ASCII and if it is, uses the configured ASCII font for it. If it is not ASCII it tries to render the glyph with the non-ASCII font. If no non-ASCII font was configured, it tries the ASCII font. If it does not find the glyph this way, it just asks the OS to give it another font to try until one is found that provides the glyph (and that is used) or it runs out of fonts to try (and a replacement character is rendered instead).

**Comment by jansol** [comment]
That said, simply having separate fonts for terminal and editor buffers for aesthetic reasons is also a reasonable thing to ask. I guess the font fallback thing belongs in its own issue.

**Comment by mikayla-maki** [comment]
I'd say leave them all here for now. This is a really useful comment to start my research on font handling in terminal emulators and it's convenient to have all the 'better font handling!' stuff in one place :D

**Comment by aexvir** [comment]
aha! nice point; I was not aware of that issue
I can see how iterm's approach would help with both problems 🙂 

yeah... my request was purely for aesthetic reasons 😅

**Comment by jansol** [comment]
FWIW, since you have a fork of font-kit and I assume you are using that for text rendering.

The `Loader` trait has a function for fetching a list of fallback fonts for a given string in a given locale, presumably to be used with a front created from a SystemSource.

(Locale is needed because some code points are shared between different glyphs because the unicode consortium decided that they are "basically the same symbol"... Unfortunately different languages have sometimes quite noticeably different ways of writing these so if you end up picking a font made for a different language you can get individual glyphs that look very out of place. See [Han unification](https://en.wikipedia.org/wiki/Han_unification))

**Comment by mikayla-maki** [comment]
This has been shipped, it should be in the settings file now! Line height will be handled later.

**Comment by SilentGlasses** [comment]
No need for a fallback, if you need the extra ligatures just use a [Nerd font](https://www.nerdfonts.com/).

They also have a Font Patcher Script so you can patch your favorite font to have the extended feature.

At best, an option would be to include a default nerd font which I understand Zed already does anyway with `FiraCode Nerd Font Mono`.
