### ISSUE TITLE
Allow re-ordering of tabs

### ISSUE THREAD

**Issue by ryanolsonx** [zed-industries/feedback#313]
**Before you begin**
Check the backlog of issues to reduce the chances of creating duplicates; if an issue already exists, place a `+1` (👍) on it.

**Is your feature request related to a problem? Please describe.**
If I have more than 4 tabs open I like to re-order them so that similar files are by each other.

**Describe the solution you'd like**
I'd like to be able to use drag n' drop to re-order tabs. If that's a lot of effort, I'd even be cool if I could re-order with a command.

**Describe alternatives you've considered**
None.

**Screenshots**
None.

**Comment by aexvir** [comment]
already reported, maybe thumbs up that one? 
https://github.com/zed-industries/feedback/issues/55

**Comment by JosephTLyons** [comment]
Yep, if you could thumbs-up the issue @aexvir linked to, that would help promote the issue in our Top-Ranking Issues issue:

- https://github.com/zed-industries/feedback/issues/52

Going to close this one in favor of the one with the votes on it already

**Comment by ryanolsonx** [comment]
Thank you! Sorry for the dup. I swear I did a couple of searches ☺️

**Comment by JosephTLyons** [comment]
> Thank you! Sorry for the dup. I swear I did a couple of searches ☺️

No worries, I wouldn't be able to find dupes if I wasn't actively reading all of the issues as they came in, it isn't always obvious how to find dupes.
