### ISSUE TITLE
Better visual feedback on pane focus

### ISSUE THREAD

**Issue by Daeraxa** [zed-industries/feedback#327]
The only apparent visual feedback on pane focus seems to be the text cursor. It is hard to see what pane is in focus, particularly when navigating via keyboard (e.g. `command + 4` to focus the 4th pane.)
You can also open additional panes without an actual editor/file open which gives no visual feedback at all.

**Describe the solution you'd like**
Some method of indicating what pane is currently active. Atom and Lapce have a small colour flair on the focused tab of the focused pane (my personal preference). VSCode dims tab titles on unfocused panes.

**Describe alternatives you've considered**
Border highlighting? Different panel background shades? Dim the line selection colour?

**Screenshots**
Atom "flair"
![image](https://user-images.githubusercontent.com/58074586/179251244-5b42ed54-6aac-4ebb-bb38-50af4c12c8e8.png)

Lapce "flair"
![image](https://user-images.githubusercontent.com/58074586/179248242-88aadf4b-33b6-4cb0-8d73-67ebe88fc778.png)

VSCode "dimming"
![image](https://user-images.githubusercontent.com/58074586/179248497-17599cd7-a554-4ece-a8ff-ed00cea9ee15.png)

**Comment by iamnbutler** [comment]
Actually working on this right now 🙂 This will be completely overhauled.

**Comment by Kethku** [comment]
Should be fixed in next release

**Comment by as-cii** [comment]
This has been fixed in Zed v0.49.0, curious to hear what you think about it @Daeraxa!

**Comment by Daeraxa** [comment]
It does seem that the effect is very dependent on the theme. So for example in either one-light or one-dark there isn't much contrast between the inactive pane tabs and the active one but if you change the theme to any of the rose-pine themes then the contrast is really stark and clear.

**Comment by iamnbutler** [comment]
> It does seem that the effect is very dependent on the theme. So for example in either one-light or one-dark there isn't much contrast between the inactive pane tabs and the active one but if you change the theme to any of the rose-pine themes then the contrast is really stark and clear.

This will get better when we ship our new theme system™️, which we are working on but takes time. By the time we hit open beta this will be significantly improved (assuming the source theme has reasonable contrast), and there will be other indicators to help with focus as well.

**Comment by Daeraxa** [comment]
Great, was going to suggest that it would be a nice bonud if there was a themeable component somewhere in the tab that could be used as an accent colour for custom themes even if it isn't wanted for the official ones.
