### ISSUE TITLE
Support opening files and folders by drag and drop from Finder

### ISSUE THREAD

**Issue by assayire** [zed-industries/feedback#333]
**Describe the solution you'd like**
Should be able to open a file or file(s) or folder(s) in Zed by dragging and dropping them in Zed. Optional/Future: When multiple folders are dropped they should open in individual windows.

**Comment by rsms** [comment]
+1 — first thing I tried (dropping a project folder onto a window)

**Comment by peterkos** [comment]
Note: not just on the app window, but also on the Dock icon

**Comment by StefKors** [comment]
+1 for opening folders and files from the dock icon

**Comment by jbergstroem** [comment]
Related/fixed similarly: Zed should also be available in the context menu:
- Right click on a markdown ->
- Open with ->
- Zed

**Comment by StefKors** [comment]
Fixed in `Zed 0.71.3` https://zed.dev/releases#zed-0.71.3

**Comment by as-cii** [comment]
Thanks for the heads-up @StefKors!

**Comment by assayire** [comment]
The issue is closed but dragging a file (or folder) into Zed does not open it. 

If the issue was closed quoting Open With in Finder way of opening then that is not the feature requested in the issue. Or is the feature being tracked in another ticket?
