### ISSUE TITLE
Override language mode

### ISSUE THREAD

**Issue by aiakared** [zed-industries/feedback#334]
**Is your feature request related to a problem? Please describe.**
Allow overriding the language mode for specific file extensions and/or the current file. This would allow for basic support in a limited number of languages that currently aren't supported by default.

**Describe the solution you'd like**
1. An option in the command palette for changing the current language mode.
2. In the `settings.json` an option similar to VS Code's `files.associations` where you can map a file extension to a language, e.g:
```json
{
    "language_overrides": {
        ".vue": "html",
    }
}
```

**Describe alternatives you've considered**
None.

**Screenshots**
N/A

**Comment by luciascarlet** [comment]
I'd like to add that this would also be useful for adding support for alternative/less common file extensions for some languages where multiple file extensions are used. An example would be .cxx and .cc for C++ code as opposed to the more common .cpp.

**Comment by JosephTLyons** [comment]
Hey @aiakared, there's a similar issue for this here, would you mind posting any of the extra details you have in this issue into that one as a comment so we can keep the 👍s on a single issue?  We use 👍s to track the importance of a feature.  Going to close this as a duplicate.

**Comment by aiakared** [comment]
Oh my bad @JosephTLyons, I wasn't able to find that issue before posting. Thanks for pointing me in the right direction, I'll post my thoughts on that issue!

**Comment by JosephTLyons** [comment]
No worries.  You have some good thoughts on this issue that I think should be taken into consideration - I would've closed the original issue in favor of this one, but its much easier to move content from here to there than move the likes from there to here.
