### ISSUE TITLE
Support to shrink and expand code blocks

### ISSUE THREAD

**Issue by rranjan14** [zed-industries/feedback#338]
**Before you begin**
Check the backlog of issues to reduce the chances of creating duplicates; if an issue already exists, place a `+1` (👍) on it.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Screenshots**
If applicable, add mockups / screenshots to help explain present your vision of the feature.

**Comment by aexvir** [comment]
not fully sure as you haven't provided much of a description, but I think this is about code folding
in that case please close this issue and add a 👍🏻 to https://github.com/zed-industries/feedback/issues/250
