### ISSUE TITLE
Zed crashing on load

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/feedback#346]
The newly released v0.48.0 version is crashing on load.  Nothing is logged into Zed.log.  Here's the Apple crash log:
[apple_log.txt](https://github.com/zed-industries/feedback/files/9136681/apple_log.txt)

**Environment:**
Zed 0.48.0 – /Applications/Zed.app
macOS 12.4
architecture x86_64

**Comment by JosephTLyons** [comment]
Feels like:

https://github.com/zed-industries/zed/issues/1343

**Comment by maxbrunsfeld** [comment]
It looks like another problem with the precompiled wasm:

```
Thread 33 Crashed:: background-executor-28
0   ???                           	       0x118fa41e6 ???
1   zed                           	       0x10e3ef4f5 wasmtime_runtime::traphandlers::catch_traps::call_closure::h5d1ac70a2412b42e + 21
2   zed                           	       0x10ec8dced wasmtime_setjmp + 109
3   zed                           	       0x10e3ef6ad wasmtime_runtime::traphandlers::catch_traps::h538d78d4183d5b45 + 109
4   zed                           	       0x10e38f177 wasmtime::func::invoke_wasm_and_catch_traps::h87fc319c28da27af + 231
5   zed                           	       0x10e3f807f _$LT$alloc..boxed..Box$LT$F$C$A$GT$$u20$as$u20$core..ops..function..FnOnce$LT$Args$GT$$GT$::call_once::h409c6b59cba9a6dd + 207
6   zed                           	       0x10e3a6dda wasmtime_fiber::unix::fiber_start::h9b9ac8b9a7e7b0b3 + 74
7   zed                           	       0x10ecbb008 wasmtime_fiber_start + 8
```

**Comment by maxbrunsfeld** [comment]
For right now, I'll remove the experimental code path that's using Wasmtime, and push up a patch release.

**Comment by maxbrunsfeld** [comment]
@JosephTLyons I believe the crashing code has been removed in Zed v0.48.1. Let me know if that release fixes the problem for you, and thanks for the report!!

**Comment by JosephTLyons** [comment]
> @JosephTLyons I believe the crashing code has been removed in Zed v0.48.1. Let me know if that release fixes the problem for you, and thanks for the report!!

Yep, all is good on my end now, Zed is launching just fine in v0.48.1.
