### ISSUE TITLE
Odd panel behaviour

### ISSUE THREAD

**Issue by kaem-e** [zed-industries/feedback#360]
### Check for existing issues

- [X] Completed

### Describe the bug

I cant tell if this is a bug or intended behaviour but seems like using the keyboard shortuct's to show and hide the various panels (namely projects and contacts) onnly wok to open the panes and don't actually close them back

### To reproduce

press cmd shift e or cmd shift c to open the projects pane or contacts pane, then try to use the same respective keybindings to close them

### Expected behavior

hitting the shortcut hides the panel in question

### Environment

Zed 0.48.1 – /Applications/Zed.app \nmacOS 12.4 \narchitecture x86_64

**Comment by JosephTLyons** [comment]
Hey @kaem-e, check out this response for clarification on what is happening.  I'm going to close this issue in favor of the previous one.

https://github.com/zed-industries/feedback/issues/223#issuecomment-1175997997

There is a pending pull request to rename:

`contacts_panel::Toggle` -> `contacts_panel::ToggleFocus`
`project_search::Toggle` -> `project_search::ToggleFocus`
