### ISSUE TITLE
Splitting with no editors open creates an unusable split area

### ISSUE THREAD

**Issue by eth0net** [zed-industries/feedback#361]
### Check for existing issues

- [X] Completed

### Describe the bug

Performing an editor split action without any open editors creates a split and leaves the original area that cannot be used, as there is no way to open an editor into the original area without closing all open editor tabs in the new areas.

### To reproduce

Open a new Zed window, perform a split, and then open an editor from a file or create a new file.

### Expected behavior

Split doesn't act if there is no editor open.

### Environment

Zed 0.47.1 – /Applications/Zed.app 
macOS 12.3.1 
architecture x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

Screenshot of a new window after recreating the steps
![Screenshot 2022-07-20 at 10 30 11](https://user-images.githubusercontent.com/1347854/179950407-201afad4-a327-4ea0-b025-233f34f2bd14.png)

**Comment by Daeraxa** [comment]
I think this isn't entirely true, this is something I came across before when logging this issue: https://github.com/zed-industries/feedback/issues/326

Basically the "empty" pane is entirely usable, it just lacks two things: 
- Visual feedback to show which pane is actually selected
- An element that one can click with a mouse to change focus to that pane

You can actually use these 'blank' panes just fine if you focus them with the keyboard (e.g. cmd + 1, cmd + n)

**Comment by eth0net** [comment]
Oo that's interesting to know, thank you! I hadn't thought about the shortcut to switch tabs, which somewhat mitigates the issue 😃 

I guess the best suggestion I have moving forward is to change it so clicking on the pane would select it for use? This would allow people to use the pane even if they don't know or think of the shortcuts. 

I also like the idea of some indication that a pane is active, maybe set the pane border to a different colour from the theme?

It might also be beneficial to show some placeholder text in a blank pane, even if it's just the pane number 😄

**Comment by Daeraxa** [comment]
> I guess the best suggestion I have moving forward is to change it so clicking on the pane would select it for use? This would allow people to use the pane even if they don't know or think of the shortcuts.

I agree, a click should be able to focus on it (if the idea of 'blank' panes is something the team is looking to keep

> I also like the idea of some indication that a pane is active, maybe set the pane border to a different colour from the theme?
> 
> It might also be beneficial to show some placeholder text in a blank pane, even if it's just the pane number 😄

Already raised :)
https://github.com/zed-industries/feedback/issues/327

**Comment by Kethku** [comment]
Should be fixed in next release

**Comment by Daeraxa** [comment]
The state itself isn't broken, it just isn't clear that it is usable and can't be clicked on to focus.
Out of interest does this change also stop new splits being made if you open them with cmd + number like this issue? https://github.com/zed-industries/feedback/issues/326

**Comment by eth0net** [comment]
> Already raised :)
> #327

Nice 😄 

> Should be fixed in next release. For now, splitting an empty pane is disabled, so you can't get into this broken state. We will address what to put there (if anything) in a future change.

Many thanks 💕
