### ISSUE TITLE
Missing scrollbars?

### ISSUE THREAD

**Issue by und3fined** [zed-industries/feedback#370]
### Check for existing issues

- [ ] Completed

### Describe the bug

I open file have many lines. But can't get scrollbars 

### To reproduce

- Open any file have many lines

### Expected behavior

Have a scrollbars showup

### Environment

Zed 0.48.1 – /Applications/Zed.app
macOS 13.0
architecture arm64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

Screen record: `https://und3fy-my.sharepoint.com/:v:/g/personal/me_cuong_lv/Ec_ixxAT6DJAkBf9v3YmFesBqrVL4d2g1eeVeuNsDTJNDw?e=rco8sh`

**Comment by JosephTLyons** [comment]
Hey @und3fined, could you put a like on this issue to help boost it in the tracking issue?  Going to close this out in favor of the existing issue:
- https://github.com/zed-industries/feedback/issues/165

**Comment by und3fined** [comment]
@JosephTLyons thanks for link to original issue
