### ISSUE TITLE
Forward and Backward Arrows

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/feedback#38]
I would love to be able to travel back and forth, between cursor jumps, via the UI.

**Comment by slightknack** [comment]
This is something I've always wanted in a text editor.

**Comment by JosephTLyons** [comment]
I've grown to really like having them.

JetBrains IDE's ship with them, but they are disabled by default - you have to have enable a specific toolbar to get them to show (view > appearance > toolbar)

<img width="144" alt="image" src="https://user-images.githubusercontent.com/19867440/173179320-356060b9-0deb-4acb-95c8-089b435ccda6.png">

Xcode ships with them

<img width="350" alt="image" src="https://user-images.githubusercontent.com/19867440/173179463-f1a93adc-6502-4e39-b858-016055bc0485.png">

VS Code does not ship with them, but there's a great package called [Back and Forth](https://marketplace.visualstudio.com/items?itemName=nick-rudenko.back-n-forth) that I've been using for about 3 year

<img width="137" alt="image" src="https://user-images.githubusercontent.com/19867440/173179408-28694838-8952-49d6-878b-1b4f07016a35.png">

I don't see them in Sublime Text, but

**Comment by as-cii** [comment]
This would be a pretty simple addition: we already have a command that you can dispatch (via `ctrl—` and `ctrl-shift—`) to navigate back and forth in the history, so it would be just a matter of displaying some buttons.

**Comment by JosephTLyons** [comment]
> This would be a pretty simple addition: we already have a command that you can dispatch (via `ctrl—` and `ctrl-shift—`) to navigate back and forth in the history, so it would be just a matter of displaying some buttons.

Yeah, I recall there being a keybinding for it, but for whatever reason, and I tend to favor key commands, but for whatever reason, I've always preferred to use the UI for back and forth actions.

**Comment by iamnbutler** [comment]
I can look in to this. Would you expect these to be in the tab bar, or in the title bar to the right of the traffic light?

**Comment by JosephTLyons** [comment]
> I can look in to this. Would you expect these to be in the tab bar, or in the title bar to the right of the traffic light?

Hmmm, that's a tricky one.  Both have pros.  Having it in the tab bar puts it closer to the code, less travel distance to get to it probably feels more natural, but the available space in the tab bar is not something that is static.  Sometimes you have 1 file open, sometimes you have 10, and every bit of that space counts - putting it near the traffic cone would prevent the tab bar from losing valuable space.  Either seem fine to me, but if I absolutely had to pick, probably next to the traffic cone, since there is some free space up there.  Curious to hear how others feel about it.

**Comment by JosephTLyons** [comment]
Then again, I don't have an eye for design, maybe it looks better to keep that top row as clutter-free as possible and put in the tab bar.  Ugh, I really don't know 😑

**Comment by iamnbutler** [comment]
Figma link: https://www.figma.com/file/2WK2NTEilTHMldL8tVg0nM/ZDS-%E2%80%93-Components?node-id=215%3A974

<img width="817" alt="CleanShot - 2022-06-20 at 13 13 11@2x" src="https://user-images.githubusercontent.com/1714999/174651219-172ce4d7-b0f7-4a16-824d-cba1385bd904.png">

Here is a first pass for the navigation arrows in the toolbar.

**Comment by JosephTLyons** [comment]
> Figma link: https://www.figma.com/file/2WK2NTEilTHMldL8tVg0nM/ZDS-%E2%80%93-Components?node-id=215%3A974
> 
> 
> 
> <img width="817" alt="CleanShot - 2022-06-20 at 13 13 11@2x" src="https://user-images.githubusercontent.com/1714999/174651219-172ce4d7-b0f7-4a16-824d-cba1385bd904.png">
> 
> 
> 
> Here is a first pass for the navigation arrows in the toolbar.

This is looking good!
