### ISSUE TITLE
Key shortcut for lsp hover

### ISSUE THREAD

**Issue by zongUMR** [zed-industries/feedback#385]
### Check for existing issues

- [X] Completed

### Is your feature request related to a problem?

No, it's not a problem at least for me, just a feature request.

### Describe the solution you'd like

When coding, we want to see the LSP documentation manually, so we need to trigger it with a shortcut

### If applicable, add mockups / screenshots to help present your vision of the feature

Neovim's built-in LSP has this support:
```
<Cmd>lua vim.lsp.buf.hover()<CR>
```
I hope Zed can add this feature as well.

**Comment by maraisr** [comment]
Emm. Not sure this is useful to folk with a mouse, you can hover just fine at the moment.

**Comment by Kethku** [comment]
There is an `editor: Hover` command which can be activated with the command palette or bound to a key using your keymap. It's also bound in vim mode to `g` `h` but has an issue where the `g` operator doesn't clear that I haven't hammered out yet.

**Comment by zongUMR** [comment]
> There is an `editor: Hover` command which can be activated with the command palette or bound to a key using your keymap. It's also bound in vim mode to `g` `h` but has an issue where the `g` operator doesn't clear that I haven't hammered out yet.

Thanks @Kethku , `editor:Hover` is what I need.
