### ISSUE TITLE
File menu seems to lack 'open recent'

### ISSUE THREAD

**Issue by rudifa** [zed-industries/feedback#395]
### Check for existing issues

- [X] Completed

### Is your feature request related to a problem?

I'm always frustrated when an editor has no option to open recently edited files

### Describe the solution you'd like

I would like to see File menu option 'open recent'

**Comment by JosephTLyons** [comment]
There is some discussion of `File > Open Recent` going on over at https://github.com/zed-industries/feedback/issues/77.  I think I will close this one out in favor of that one, feel free to put a 👍 on that issue and add a comment if there is any extra detail you want to mention.
