### ISSUE TITLE
Same project listed multiple times

### ISSUE THREAD

**Issue by fdionisi** [zed-industries/feedback#40]
**Describe the bug**
Opening and closing a project multiple times keep adding it to the Online's projects list multiple times.

**To Reproduce**
- Open Zed
- Open an offline Project (doesn't seem to be an issue with online ones)
- Close the project (the Project is not removed from the Online's projects list)
- Open the same Project

> Keep closing and opening to add more and more entries of the same project

**Expected behavior**
Only one offline Project is present in the projects list.

**Screenshots**

<img width="241" alt="Screenshot 2022-06-11 at 19 27 04" src="https://user-images.githubusercontent.com/8927326/173201390-f49e97a8-0e0a-4557-b7c8-ef2184c1cfdf.png">

**Environment:**
 - Architecture: Apple Silicon
 - Mac OS Version: 12.1
 - Zed Version: 0.38.0

**Comment by JosephTLyons** [comment]
I think that screenshot from VS Code

**Comment by fdionisi** [comment]
> I think that screenshot is from VS Code

Oooops! Indeed, thank you @JosephTLyons for the heads up

**Comment by JosephTLyons** [comment]
There we go :)

**Comment by maxbrunsfeld** [comment]
Thank you for the report @fdionisi. The fix will ship in Zed 0.40.
