### ISSUE TITLE
References tab - hide list item when the reference is removed

### ISSUE THREAD

**Issue by stjepangolemac** [zed-industries/feedback#426]
### Check for existing issues

- [X] Completed

### Is your feature request related to a problem?

When I remove the reference the list item in the references tab stays visible. 

### Describe the solution you'd like

Hide the list item when the reference gets deleted. This is already the case for the errors tab where the item gets removed when it's resolved.

**Comment by JosephTLyons** [comment]
Hey @stjepangolemac - would you be able to shoot a screenshot demonstrating this?  I'm trying to reproduce it based on the actions you described, but I'm not seeing it.  I may be misinterpreting what you're doing.

**Comment by mikayla-maki** [comment]
This is by design! We want multi buffers to stay stable when you're editing them so that things aren't jumping out from under you. We plan on adding a manual refresh button for this use case :)
