### ISSUE TITLE
Focus file when it's opened by clicking on it the project panel

### ISSUE THREAD

**Issue by stjepangolemac** [zed-industries/feedback#428]
### Check for existing issues

- [X] Completed

### Is your feature request related to a problem?

1. I click a file from the project panel to open it
2. The file is opened but the editor is not focused
3. I try to switch tabs with `Cmd+Shift+{` and `Cmd+Shift+}` but it doesn't work

### Describe the solution you'd like

Focus the opened file when it's just opened from the project panel.

**Comment by stjepangolemac** [comment]
Was this fixed or canceled?

**Comment by mikayla-maki** [comment]
Fixed in the next release!

**Comment by JosephTLyons** [comment]
Hmm, I grabbed a build off of CI and this doesn't seem to be working for me.  Does this work for you @mikayla-maki?

**Comment by mikayla-maki** [comment]
Oh good point, thanks for the catch @JosephTLyons

**Comment by mikayla-maki** [comment]
Hmmm, this seems to be intentional, it only moves focus if you double (or more) click

**Comment by JosephTLyons** [comment]
> Hmmm, this seems to be intentional, it only moves focus if you double (or more) click

Ahh ok, that makes sense.  I didn't try to double click.

**Comment by JosephTLyons** [comment]
Since this is implemented, I'm going to go ahead and close it out.  If you have any issues with this @stjepangolemac, feel free to open another issue.
