### ISSUE TITLE
cmd-9 does not open contacts

### ISSUE THREAD

**Issue by MikeSofaer** [zed-industries/feedback#433]
### Check for existing issues

- [X] Completed

### Describe the bug

https://zed.dev/docs/tour says that cmd-9 opens contacts but it does not.

### To reproduce

press cmd-9

or

go to https://zed.dev/docs/tour

### Expected behavior

contacts should open

or

page should not say cmd-9 opens contacts

### Environment

Zed 0.50.0 – /Applications/Zed.app 
macOS 11.6.1 
architecture x86_64

**Comment by JosephTLyons** [comment]
Ah yeah, that is an outdated command, should be:

"cmd-shift-b": "workspace::ToggleRightSidebar"

That will need to be addressed in the Tour of Zed documentation, but you can look up all the current default keybindings directly within Zed by using the Zed drop down menu > Preferences > Open Default Key Bindings.  You can also find this ion the Command Palette (`cmd-shift-p` to open)

**Comment by iamnbutler** [comment]
This should be fixed, I'll close this when changes deploy.

**Comment by iamnbutler** [comment]
Thanks for catching this!
