### ISSUE TITLE
Crash when pressing cmd-s with a japanese keyboard layout

### ISSUE THREAD

**Issue by aikan-umetsubo** [zed-industries/feedback#444]
### Check for existing issues

- [X] Completed

### Describe the bug

Zed crashes when I just pressed Cmd+S to save a file.

Below are the messages in system.log.

```
Aug 17 06:10:59 shirley com.apple.xpc.launchd[1]: Coalition Cache Hit: app<application.dev.zed.Zed.8692009602.8692009607(502)> [35358]
Aug 17 06:11:10 shirley com.apple.xpc.launchd[1] (application.dev.zed.Zed.8692009602.8692009607[10192]): Service exited with abnormal code: 101
```

### To reproduce

1. Open Zed.
2. Press Cmd+S or Cmd+O.

I tried Cmd+[A-Z] and found that S and O produce the same bug. Clicking File -> Save of menu bar didn't reproduce this bug.

### Expected behavior

The file is saved

### Environment

```
Zed 0.50.0 – /Applications/Zed.app \nmacOS 11.6.7 \narchitecture x86_64
```

### If applicable, add mockups / screenshots to help explain present your vision of the feature

n/a

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue

[Zed.log](https://github.com/zed-industries/feedback/files/9354842/Zed.log)

**Comment by maxbrunsfeld** [comment]
Stack trace from the logs:

1. Opening files

```
21:33:12 [ERROR] thread 'main' panicked at 'already mutably borrowed: BorrowError': crates/gpui/src/app.rs:350   0: backtrace::backtrace::trace
   8: core::result::unwrap_failed
   9: <gpui::app::WindowInputHandler as gpui::platform::InputHandler>::selected_text_range
  10: gpui::platform::mac::window::selected_range
  ...
  42: <gpui::platform::mac::platform::MacForegroundPlatform as gpui::platform::ForegroundPlatform>::prompt_for_paths
  43: gpui::app::MutableAppContext::add_global_action::{{closure}}
  44: gpui::app::MutableAppContext::dispatch_global_action_any
  45: gpui::app::MutableAppContext::dispatch_action_any
  46: gpui::app::MutableAppContext::dispatch_keystroke
  47: gpui::app::MutableAppContext::open_platform_window::{{closure}}
  48: gpui::platform::mac::window::handle_key_event
  ...
```

2. Saving:

```
21:33:56 [ERROR] thread 'main' panicked at 'already mutably borrowed: BorrowError': crates/gpui/src/app.rs:350   0: backtrace::backtrace::trace
   8: core::result::unwrap_failed
   9: <gpui::app::WindowInputHandler as gpui::platform::InputHandler>::selected_text_range
  10: gpui::platform::mac::window::selected_range
  ...
  41: <gpui::platform::mac::platform::MacForegroundPlatform as gpui::platform::ForegroundPlatform>::prompt_for_new_path
  42: workspace::Workspace::save_active_item
  43: gpui::app::MutableAppContext::add_action_internal::{{closure}}
  44: gpui::app::MutableAppContext::dispatch_action_any
  45: gpui::app::MutableAppContext::dispatch_keystroke
  46: gpui::app::MutableAppContext::open_platform_window::{{closure}}
  47: gpui::platform::mac::window::handle_key_event
  ...
```

**Comment by maxbrunsfeld** [comment]
Can you provide any more information about the state of the editor before you typed `cmd-s` or `cmd-o`?

**Comment by aikan-umetsubo** [comment]
@maxbrunsfeld

> Can you provide any more information about the state of the editor before you typed cmd-s or cmd-o?

Pressing cmd-s or cmd-o just after opening Zed reproduced this bug.

> What keyboard layout do you use? Are you using any control / accessibility tools that could be controlling the Zed application?

I'm using Japanese keyboard layout and don't use any control / accessibility tools.

**Comment by maxbrunsfeld** [comment]
Ok, I can reproduce this with the Japanese keyboard layout. Thank you for the report!

**Comment by as-cii** [comment]
A fix for this will go out with the next release, thank you so much for the feedback! 💯

**Comment by aikan-umetsubo** [comment]
Thank you so much for a quick fix! 😺
