### ISSUE TITLE
Use Alacritty Config from User Profile

### ISSUE THREAD

**Issue by corysm1th** [zed-industries/feedback#460]
### Check for existing issues

- [X] Completed

### Is your feature request related to a problem?

I have Alacritty installed already. With Zed's built-in terminal, I have to manage duplicate configs.

### Describe the solution you'd like

Have Zed's built in terminal use my existing Alacritty config.

**Comment by mikayla-maki** [comment]
I've considered doing this, but most of their configurations just don't apply to our use case. Further, I plan on eventually supporting things Alacritty does not, like ligatures, which require their own settings. There's also issues with how these two track each other, do Alacritty settings overrride ours? Do we have a one time 'Your settings are empty, synchronize with alacritty?' button? etc.

But also just having a smart default where, on boot up, it silently populates your settings with a subset of Alacritty's settings (along with a comment mentioning that it did this) could work. What kind of settings would you want to have synchronized?

**Comment by corysm1th** [comment]
Good points. It looks like I only configure font faces, font size, and colors. So if you're inheriting from the editor, that's probably the better design.

Sorry... should have thought it through.

**Comment by mikayla-maki** [comment]
Don’t worry about it, it’s literally my job to think things through 😄. I’m going to close this for now, but with the caveat that I think Zed could be smarter here.
