### ISSUE TITLE
Modal (Vim style) Editing

### ISSUE THREAD

**Issue by corysm1th** [zed-industries/feedback#461]
### Check for existing issues

- [X] Completed

### Is your feature request related to a problem?

Not related to a problem, just a preference.

### Describe the solution you'd like

Vim-style modal editing. The vs code community accomplished this with an extension, but it's not as good as having it as a native feature of the editor.

**Comment by ForLoveOfCats** [comment]
Zed has a builtin Vim mode which can be enabled by adding `"vim_mode": true` to your settings.json :)

It is important to note that this feature is still under active development and may not yet cover everything needed but is of fairly high importance to us

You can find a list of other configurable Zed settings here https://zed.dev/docs/configuring-zed
