### ISSUE TITLE
Remember screen size through restarts

### ISSUE THREAD

**Issue by stjepangolemac** [zed-industries/feedback#462]
### Check for existing issues

- [X] Completed

### Is your feature request related to a problem?

I always use Zed in fullscreen mode but every time I start it up it starts in windowed mode.

### Describe the solution you'd like

Remember the last used mode and use it when starting up.

**Comment by stjepangolemac** [comment]
I looked for duplicates beforehand but somehow missed this one. Thanks.

**Comment by JosephTLyons** [comment]
> I looked for duplicates beforehand but somehow missed this one. Thanks.

No problem at all.  Dupes aren't always easy to spot.
