### ISSUE TITLE
The vim mode is enabled not only in the editor, but also in the command palette

### ISSUE THREAD

**Issue by amaany3** [zed-industries/feedback#475]
### Check for existing issues

- [X] Completed

### Describe the bug

When vim mode is enabled, it is activated not only when editing files, but also when entering the command palette.
The problem with this is that you have to type escape twice to cancel the use of the command palette.
Also, the command palette usually does not require a rich input method.

### To reproduce

Open the command palette with vim mode enabled

### Expected behavior

Text input with vim mode disabled

### Environment

Zed 0.52.0 – /Applications/Zed.app
macOS 12.5
architecture arm64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="545" alt="スクリーンショット 2022-08-26 18 54 36" src="https://user-images.githubusercontent.com/25783732/186878852-2853e1fd-f370-4524-a458-98fd3e2fc889.png">

**Comment by lucastrvsn** [comment]
I found this to be really great. Can we have like a "proper" way of handling the vim mode inside those text fields? xD

**Comment by Kethku** [comment]
@lucastrvsn I'd be interested in your thoughts on what "proper" integration would be like. I like having the ability to access vim mode in the single line editors, but there are some users experience issues like the one above that can make that hard. If you have any thoughts, I'd love to hear them

**Comment by lucastrvsn** [comment]
> @lucastrvsn I'd be interested in your thoughts on what "proper" integration would be like. I like having the ability to access vim mode in the single line editors, but there are some users experience issues like the one above that can make that hard. If you have any thoughts, I'd love to hear them
> 
> 

Thank you for reaching out! I think the best way I can describe this is the way we can use our shell with vim mode. Like when we're using zsh with vim enable:

- shell starts in "insert mode"
- <ESC> go to "normal mode" (with a subset of vim commands restricted to one line and all normal things like key i to go back to insert mode in the cursor position)
- <Enter> submit the command in all modes

I think this will be the best way possible to have something like this!

For users who don't want that, made can expose a new option in settings to disable vim mode in text fields?

**Comment by Kethku** [comment]
I *think* this is how vim mode works in things like the command palette? I think the remaining gap is to provide an option to just never use vim mode in single line editors.

If it doesn't work like that now though I consider that a bug.

**Comment by lucastrvsn** [comment]
> I _think_ this is how vim mode works in things like the command palette today? I think the remaining gap is to provide an option to just never use vim mode in single line editors.
> 
> If it doesn't work like that now though I consider that a bug.

Oh yes, that's my bad.

Maybe add a default mapping to CTRL-c to exit the current "modal" would be great too, because now IIRC, CTRL-c just exist the "insert mode" to "normal mode" instead of cancel the whole action (like in shell)

**Comment by Kethku** [comment]
thats a good thought. I'll look into doing this soon TM

**Comment by restfuladi** [comment]
When leaving a command palette or another overlay, the editor should always revert back to normal mode. This is the default behavior in Vim, Neovim, and all the Vim plugins for other editors I've tried. I find myself undoing almost every time.

**Comment by dangh** [comment]
> When leaving a command palette or another overlay, the editor should always revert back to normal mode. This is the default behavior in Vim, Neovim, and all the Vim plugins for other editors I've tried.

Since it's the default behavior I'm assume there's an option to turn it off? I personally found it's unintuitive to loose the state in the buffer.

**Comment by restfuladi** [comment]
> 

Fair enough. But having insert mode activated for you unexpectedly is even more unintuitive IMO.
