### ISSUE TITLE
Lock projects for collaboration by default

### ISSUE THREAD

**Issue by stjepangolemac** [zed-industries/feedback#498]
### Check for existing issues

- [X] Completed

### Is your feature request related to a problem?

When I start Zed it leaks project names to potential collaborators.

### Describe the solution you'd like

Start Zed with all projects locked so that I can explicitly allow some of them to be collaborated on.

**Comment by JosephTLyons** [comment]
Hey @stjepangolemac, try adding this setting to your settings.json file:

```json
"projects_online_by_default": false,
```

**Comment by stjepangolemac** [comment]
That did it, thank you 👍

**Comment by JosephTLyons** [comment]
If you ever want to skim what settings are available, you can use the "zed: open default settings" action in the command palette.
