### ISSUE TITLE
Programs with large amounts of output in the terminal cause Zed to lag

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/feedback#506]
### Check for existing issues

- [X] Completed

### Describe the bug

Programs with many lines of output causes Zed to lag.  After a few moments, performance returns to normal - I'm guessing this is something "catching up?"  This actually *might* be a dupe or a known issue - I vaguely recall seeing this mentioned somewhere else, but can't seem to find the source.

### To reproduce

1. Run the following Rust program:

```rust
fn main() {
    for _ in 0..1_000_000 {
        println!("Hi");
    }
}
```
2. Try editing a file and notice the lag, which eventually goes away

### Expected behavior

-

### Environment

Zed 0.53.1 – /Applications/Zed.app
macOS 12.4
architecture x86_64

**Comment by mikayla-maki** [comment]
woah, I thought I already tested for this stuff using `yes`. I'll check this out Monday, thanks for the catch!

**Comment by mikayla-maki** [comment]
@JosephTLyons  conducted further tests and discovered 2 interesting parts of this:
1) The slow down continues *after* the terminal

**Comment by mikayla-maki** [comment]
From @ForLoveOfCats, Python buffers output before calling write, and Rust does not, this is probably why Rust produces a massive slow down and Python does not in this specific case. This is probably another time where my code is responding too eagerly to terminal events...

**Comment by mikayla-maki** [comment]
fixed by squashing wakeups
