### ISSUE TITLE
Add an option for treating alt as the meta key

### ISSUE THREAD

**Issue by mikayla-maki** [zed-industries/feedback#507]
### Check for existing issues

- [X] Completed

### Is your feature request related to a problem?

emacs users are sad :(

I think the meta key code == esc key code (`0x1b`)

### Describe the solution you'd like

Have a setting for it

**Comment by mikayla-maki** [comment]
This should be added in the next release. That said, I don't use emacs and may have gotten some of the finer details wrong, please re-open if something comes up.

**Comment by chriskrycho** [comment]
Thank you! See also a related issue I opened, #447, which gets at the general set of CoreText shortcuts (all Emacs-derived!) which are normal in macOS apps.

**Comment by mikayla-maki** [comment]
Interesting, never heard of a kill ring before!

**Comment by chriskrycho** [comment]
Somebody in the early Mac OS X days (or possibly all the way back in the NeXT days!) *loved* Emacs, apparently. :joy:

**Comment by mikayla-maki** [comment]
I love the way UI/UX echos through time like that. Someone just really likes a thing, makes a thing happen, and now decades later we're all working on maintaining it. It's wonderful 😂
