### ISSUE TITLE
Typescript server will not run or download

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/feedback#509]
### Check for existing issues

- [X] Completed

### Describe the bug

I opened a typescript project, opened a typescript file, and hit save - the server did not start up.
I typed an error and hit save - the server did not come up or report an error.
I deleted the language server, reopened the project, resaved a typescript file, and the server did not download.

### To reproduce

-

### Expected behavior

-

### Environment

Zed 0.53.1 – /Applications/Zed.app
macOS 12.4
architecture x86_64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue

```log
Caused by:
    0: IO error: Connection reset by peer (os error 54)
    1: Connection reset by peer (os error 54)
23:24:27 [INFO] set status on client 0: ConnectionLost
23:24:27 [INFO] set status on client 0: Reauthenticating
23:24:27 [INFO] set status on client 0: Reconnecting
23:24:27 [INFO] connected to rpc endpoint https://collab.zed.dev/rpc
23:24:28 [ERROR] not connected
23:24:28 [ERROR] not connected
23:24:28 [INFO] add connection to peer
23:24:28 [INFO] add_connection;
23:24:28 [INFO] set status to connected 53
23:24:28 [INFO] set status on client 0: Connected { connection_id: ConnectionId(53) }
23:28:46 [ERROR] No such file or directory (os error 2)
23:28:49 [WARN] incoming response: unknown request connection_id=53 message_id=11 responding_to=9
23:29:12 [INFO] open paths ["/Users/josephlyons/Desktop/move/zed/zed.dev"]
23:29:15 [ERROR] No such file or directory (os error 2)
23:30:53 [ERROR] No such file or directory (os error 2)
23:36:03 [ERROR] unexpected item event after pane was dropped
23:36:04 [WARN] incoming response: unknown request connection_id=53 message_id=24 responding_to=116
23:36:06 [INFO] open paths ["/Users/josephlyons/Library/Application Support/Zed/languages"]
23:36:08 [ERROR] No such file or directory (os error 2)
```

**Comment by JosephTLyons** [comment]
I don't think this is a duplicate of: 

- https://github.com/zed-industries/feedback/issues/445

Because I don't see the same `No such file or directory (os error 2)` error in the log on this issue.

**Comment by Kethku** [comment]
Can you try renaming `~/.zed/typescript-language-server` to something like `broken-typescript-language-server` and rerunning zed? I think its possible that it failed in an update.

If that works, if you could upload the renamed folder for us to inspect that would help figure out what went wrong!

**Comment by JosephTLyons** [comment]
Is the directory still being used?  I think the language servers on my system are in `~/Library/Application Support/Zed/languages`

**Comment by Kethku** [comment]
Ah my bad. Yes same instructions but for the other location. Good catch.

**Comment by JosephTLyons** [comment]
Alright, I deleted the entire languages directory, closed Zed, and reopened it.  The languages directory was recreated.  I opened the typescript project and saved a file and the server was installed, but I'm still getting no diagnostics.

This is with the Zed.dev project.

**Comment by Kethku** [comment]
Very strange. This is still true after running `restart language server` from the command palette? Just thinking of things to try.

I'd also be interested to see your log file after the redownload

**Comment by JosephTLyons** [comment]
yeah I just tried to do a the server restart, but nothing changed on my end.  Here are the lines after opening the typescript file and trying to save the project

```log
00:28:58 [INFO] open paths ["/Users/josephlyons/Desktop/move/zed/zed.dev"]
00:29:06 [ERROR] invalid header
00:29:06 [ERROR] oneshot canceled
00:29:06 [ERROR] oneshot canceled
00:29:06 [ERROR] Broken pipe (os error 32)
00:29:10 [ERROR] unexpected item event after pane was dropped
```

**Comment by Kethku** [comment]
Very strange. Invalid header to me says that the language server isn't getting run correctly. Could you tell me what files are in the typescript language server folder?

**Comment by JosephTLyons** [comment]
The only file is `typescript-4.8.3:server-1.2.0`

**Comment by JosephTLyons** [comment]
Interestingly enough, the project and the Typescript server work on my MacBook, but not my iMac.  I'll try to narrow down what the differences might be.

**Comment by JosephTLyons** [comment]
Looks like the server is failing to run.  When I try to run it via the command line on my iMac, I get:

```
> node cli.js --stdio

internal/modules/cjs/loader.js:1174
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/josephlyons/Library/Application Support/Zed/languages/typescript-language-server/typescript-4.8.3:server-1.2.0/node_modules/typescript-language-server/lib/cli.js
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1174:13)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  code: 'ERR_REQUIRE_ESM'
}
```

This doesn't happen when running it on my MacBook.  Not sure what this means just yet - need to become more familiar with JS.

**Comment by maxbrunsfeld** [comment]
What version of Node are you using on the iMac?

**Comment by JosephTLyons** [comment]
> What version of Node are you using on the iMac?

v12.16.1
