### ISSUE TITLE
FAQ 🙋‍♀️

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/feedback#515]
- [Will Zed be available on Linux/Windows/Web?](https://github.com/zed-industries/feedback/issues/174)
- Where do I find Zed's log files?
    - Zed's log file can be found at: `~/Library/Logs/Zed/Zed.log`
    - Additionally, the last 1000 lines of Zed's log file can be opened in a Zed buffer by opening the command palette (`cmd-shift-p`) and running the action `zed: open log`

**Comment by yashank09** [comment]
Hello! Is this a place public can add/ask FAQs too? 

I would love to know if there's any vision for community extensions! Anything planned?

**Comment by yashank09** [comment]
Following the above, would someone also explain the technical vision of this project? Is Zed going to be a minimal IDE with extensions(like ST; VSC seems too bloated out of box); or is it going to be a fully packed IDE like JetBrains does? This way we can understand if a new feature request is needed or it could be eventually handled by an extension.

**Comment by JosephTLyons** [comment]
> Hello! Is this a place public can add/ask FAQs too?
> 
> I would love to know if there's any vision for community extensions! Anything planned?

Hey @yashank09, sorry this slipped by me.  We do intend to allow Zed to be extensible, through packages / plugins, but we don't currently know what that looks like right yet.  With Atom, the core principle was to have a "hackable" editor, with Zed, the core principle is to be performant.  We need to spend some time thinking about how to develop a plugin ecosystem that doesn't encourage plugins that will ultimately slow the editor down - we always want Zed to be fast.

**Comment by JosephTLyons** [comment]
Closing this in favor of the updated FAQ section landing shortly
