### ISSUE TITLE
Changed username resulted in loosing access to releases page

### ISSUE THREAD

**Issue by s-h-o-t** [zed-industries/feedback#516]
I recently changed username on GitHub from TheFoolishPupil to s-h-o-t and no longer have access to the releases page

**Comment by iamnbutler** [comment]
We just discussed a change that will prevent this from happening. It should come in the near future. For now, I've fixed your account manually. Let me know if it doesn't work!

**Comment by s-h-o-t** [comment]
works. Thanks (:

**Comment by s-h-o-t** [comment]
Hold up, I jumped the gun it seems. I now see my old username as an online contact and the sign in button doesn't do anything

![Screen Shot 2022-09-21 at 00 43 16](https://user-images.githubusercontent.com/43202406/191377787-9f311678-1892-4baf-b12d-16b28c72929d.png)

**Comment by iamnbutler** [comment]
Can you fully close Zed (or if that doesn't work, delete the app and redownload it from the site) and let me know if you still have this issue?

**Comment by s-h-o-t** [comment]
Same issue after a fresh install

**Comment by iamnbutler** [comment]
I found the issue, working to resolve now!

**Comment by maxbrunsfeld** [comment]
Ok, can you try logging again @s-h-o-t?

**Comment by s-h-o-t** [comment]
<img width="366" alt="Screen Shot 2022-09-21 at 19 37 57" src="https://user-images.githubusercontent.com/43202406/191573237-5fc1e745-9837-4960-8891-56d98719697d.png">
Looks like everything is working :) I can't remember if I'm supposed to see myself or not but you guys will know that.

**Comment by maxbrunsfeld** [comment]
Yeah, that's the expected behavior for now. Thanks for reporting the problem to us, and sorry for the trouble!

**Comment by s-h-o-t** [comment]
The problem has returned. I don't have access to the release notes and see the option to sign up for the waitlist. Zed itself works fine and just updated to 0.55.0

**Comment by maxbrunsfeld** [comment]
Are you logged into zed.dev? If not, are you able to log in?
