### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by zlunchbox** [zed-industries/feedback#520]
### Check for existing issues

- [X] Completed

### Describe the bug

Zed 0.54.0 receives a SIGABRT shortly after start-up, apparently because of a missing library (libc++.1.dylib). [Here's the report.](https://github.com/zed-industries/feedback/files/9612228/zed-crash-log.txt) Note that 0.53.1 launches successfully; after this continued to occur, I uninstalled and downgraded to that version (before the automatic update brought me back up).

Seems like the library should be in my /usr/lib, but it isn't; there is libstdc++.dylib and libstdc++.6.dylib though.

### To reproduce

Launch Zed.

### Expected behavior

Zed launches without crashing.

### Environment

Zed 0.54.0 – /Applications/Zed.app 
macOS 11.7 
architecture x86_64

**Comment by as-cii** [comment]
Thank you so much for the report! 💯 We just released a new version of Zed that addresses this issue, can you try updating and seeing if you can launch it now?
