### ISSUE TITLE
`page up` and `page down` don't work

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/feedback#539]
### Check for existing issues

- [X] Completed

### Describe the bug

@Windsoilder discovered that these actions are currently doing nothing

### To reproduce

-

### Expected behavior

-

### Environment

Zed 0.55.0 – /Applications/Zed.app
macOS 12.6
architecture x86_64

**Comment by WindSoilder** [comment]
Oh, hi, I just read the top-ranking issues, and find it's duplicated with #191

**Comment by JosephTLyons** [comment]
Thanks for catching this, going to close it in favor of that one.  Feel free to add a 👍 on the original to upvote it.
