### ISSUE TITLE
Deploying dock causes project panel to shrink

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/feedback#545]
### Check for existing issues

- [X] Completed

### Describe the bug

When the dock is positioned in the right side of the editor, deploying it forces the already-open file over to the left, subsequently horizontally shrinking the project panel.

### To reproduce

-

### Expected behavior

Allow the dock to "consume" enough of the already-open tab such that it doesn't push that tab to the left and onto the project folder.

### Environment

Zed 0.55.0 – /Applications/Zed.app
macOS 12.6
architecture x86_64

**Comment by mikayla-maki** [comment]
This can get very bad 

https://user-images.githubusercontent.com/2280405/195171762-afe58b25-7e5d-4492-9da0-31b6a77ad48a.mov
