### ISSUE TITLE
Incorrect response when input in rust file

### ISSUE THREAD

**Issue by zhang0098** [zed-industries/feedback#556]
### Check for existing issues

- [X] Completed

### Describe the bug

try to input  the following in a  .rs file: 
 "{}
Except to get  : "{}"  
Actual result: "{"

### To reproduce

input "{}  in .rs file.

### Expected behavior

Should get "{}"

### Environment

Zed 0.59.0 – /Applications/Zed.app \nmacOS 12.6 \narchitecture x86_64

**Comment by JosephTLyons** [comment]
Hey @zhang0098, I checked in VS Code and Sublime Text and they both seem to handle the input the same as Zed.  I'm curious If you are currently using an editor that performs the autocompletion you mentioned, or if this is just something that has been on your want list for a future editor.

**Comment by zhang0098** [comment]
> Hey @zhang0098, I checked in VS Code and Sublime Text and they both seem to handle the input the same as Zed. I'm curious If you are currently using an editor that performs the autocompletion you mentioned, or if this is just something that has been on your wish list for a future editor.

It's should be a bug in Zed, and now fixed in version 0.60.4
Thanks.
