### ISSUE TITLE
Python constant color lacks contrast on one-dark theme

### ISSUE THREAD

**Issue by lancelote** [zed-industries/feedback#567]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Python's constant foreground highlighting color on the one-dark theme lacks contrast. A comment is brighter than a constant

<img width="596" alt="constant" src="https://user-images.githubusercontent.com/2500320/194960119-fe938e74-bd3a-401b-ac50-9fbcd4378258.png">

### Expected behavior

- Constant color is brighter than the comment one
- Constant color has a decent contrast

### Environment

Zed 0.59.0 – /Applications/Zed.app 
macOS 12.4 
architecture arm64

**Comment by SeparateRecords** [comment]
<img width="193" alt="CleanShot 2022-10-11 at 15 35 37@2x" src="https://user-images.githubusercontent.com/52195359/194997973-035e8698-0dd0-4250-b728-46a0d669b68e.png">
Also true for booleans in toml and TS

**Comment by iamnbutler** [comment]
Found the problem, working on this one 👍

**Comment by JosephTLyons** [comment]
This should be fixed in the next update

**Comment by jack4818** [comment]
Hi, at least my end running `0.61.1` I still have syntax highlighting which feels wrong.


Here is how GitHub renders the same code

```py
# This is a code comment
CONSTANT_PI = 3.14 # Denote constant with CAPS
bool_true  = True  # Declare bools
bool_false = False
```

Here are screenshots from Zed using one dark / light

<img width="793" alt="Screenshot 2022-10-26 at 6 07 24 pm" src="https://user-images.githubusercontent.com/44242839/198091438-6c5ebcc1-2eec-4bd6-b7d3-6acc906a126f.png">
<img width="793" alt="Screenshot 2022-10-26 at 6 07 33 pm" src="https://user-images.githubusercontent.com/44242839/198091455-fe1a1a60-40ed-40b3-9b43-0e00519378ad.png">

**Comment by JosephTLyons** [comment]
Hi @jack4818 - this will go out with out next non-patch release.  I probably jumped the gun on closing this out, which led to confusion.  My apologies.
