### ISSUE TITLE
Add support for New Line Above

### ISSUE THREAD

**Issue by mike-engel** [zed-industries/feedback#572]
### Check for existing issues

- [X] Completed

### Is your feature request related to a problem?

It's a trivial problem, but as of this writing, there are commands that can be mapped to keys for `editor::NewLine` and `editor::NewLineBelow`. I'm coming from VS Code, where there's also the ability to create a new line above the selection (`shift-o` in vim I guess) that isn't present in Zed. 

### Describe the solution you'd like

I'd like to be able to map a key to something like, `editor::NewLineAbove`, which would create a new line and focus the cursor above the current selection. This is the opposite behavior of `editor::NewLineBelow`. Thanks!

**Comment by rkusa** [comment]
Can actually already be done via a custom keybinding. Hit CMD+K, CMD+S to open your keybindings (or open them via Zed preferences), and add the following:

```json
[
  {
    "context": "Editor",
    "bindings": {
      "cmd-shift-enter": "vim::InsertLineAbove"
    }
  }
]
```

I second that a default keybinding for that would be very welcome.

This might also be a duplicate of #4.

**Comment by mike-engel** [comment]
Thanks @rkusa! That should work, but this also looks like a duplicate of #4, so I'll close in favor of that
