### ISSUE TITLE
Do you guys consider open sourcing GPUI?

### ISSUE THREAD

**Issue by schwrzstrbn** [zed-industries/feedback#573]

**Comment by iamnbutler** [comment]
The best place to discuss open source for now is this discussion: https://github.com/zed-industries/feedback/discussions/289

We have discussed open sourcing GPUI in the past, for now we don't have any specific decisions to share.

**Comment by gmile** [comment]
@iamnbutler I just came across this issue, and clicking a link from your message returns a 404. Did the discussion move elsewhere? If yes, where?
