### ISSUE TITLE
Use zed as `EDITOR` for git

### ISSUE THREAD

**Issue by ruza-net** [zed-industries/feedback#574]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I want to use zed as an `EDITOR`, which is used by e.g. git to edit rebase todos and commit messages.

Zed `cli` can open such a file, but since it spawns a new zed tab and then exits, git doesn't wait for me to edit the todo / commit message.

On the other hand, the program `Zed.app/Contents/MacOs/zed` allows me to edit the file properly, but it doesn't signal to git that the file closed. Hence in this case, git waits indefinitely.

### Expected behavior

Zed should signal that it closed a given file.

I don't know how the file manipulations are implemented in zed differently from other editors, so I can't say what exactly that interaction should look like.

### Environment

Zed 0.59.0 – /Applications/Zed.app 
macOS 12.4 
architecture x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

1. `git rebase -i ...`
2. Zed opens `git-rebase-todos` in a new window
3. Edits are made and window is closed.
4. git performs the rebase

**Comment by maxbrunsfeld** [comment]
Sorry, we are  missing documentation for this. To install the `zed` command line tool, click `Zed > Install CLI`  in the application menu. You can then use Zed as your terminal by setting `EDITOR=zed --wait`.

**Comment by ruza-net** [comment]
@maxbrunsfeld Thanks! This resolves the issue.

**Comment by tiye** [comment]
`zed -w` works for me. I also notice it does not bring focus back to CLI after I finished writing in the new Zed window, any trick to restore focus back to terminal?
