### ISSUE TITLE
zed automatically cuts lines to 80 chars when pasting

### ISSUE THREAD

**Issue by newearthmartin** [zed-industries/feedback#593]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When pasting text, Zed automatically adds a line break at 80 chars.

### Expected behavior

Zed does not alter pasted lines

### Environment

Zed 0.60.4 – /Applications/Zed.app \nmacOS 12.6 \narchitecture arm64

**Comment by TerminalFi** [comment]
@newearthmartin Is this still occurring in the latest release? I am unable to reproduce

**Comment by newearthmartin** [comment]
Hi, yes but it's not exactly that it's cutting the lines. More that the display is wrapepd at 80 chars. Not sure if it's a bug or a feature. 

I'm trying to paste this:

`[{"selector": ".blog-archive-list .blog-link", "value": "November 2019", "language": "en", "translation": "November 2019"}, {"selector": "id:form_submit_button", "value": "Send", "language": "en", "translation": "Send"}]`

And I see this:

<img width="1440" alt="Screenshot 2022-11-04 at 13 49 24" src="https://user-images.githubusercontent.com/1507266/200031108-d42faa62-f5c9-4fce-93ad-075f7ca30733.png">

However, it still shows everyting is in line 1 so it's not cut. It's just wrapped. 

I would expect to have the line take as many chars as possible and then be wrapped. Then I also would expect to be able to "toggle wrap" but I don't seem to find that option.

**Comment by mikayla-maki** [comment]
I believe it's a setting called 'soft_wrap', which is set to '80 chars' for plain text files. As the buffer you have open is the default buffer, it's type is interpreted as plain text. Note that this shouldn't happen in most other kinds of files (e.g. source code files). If you want to change this behavior, you can add it to your personal settings. We include the default settings (cmd-shift-p: "open default settings") so people can discover the syntax and options available.

We can probably make all this more intuitive though, pending a better settings experience overall! Thanks for the report :)

**Comment by newearthmartin** [comment]
Hi, thanks for clarifying. It's nice to be able to edit the soft wrap "strategy". However, for turning wrapping on and off it's pretty standard to have a menu option. I think many users will be looking for that.

**Comment by mikayla-maki** [comment]
Agreed! We have lots to do 😅
