### ISSUE TITLE
Documentation-on-hover is drawn partially outside the application window when displayed together with an error.

### ISSUE THREAD

**Issue by s-h-o-t** [zed-industries/feedback#618]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Hovering over particular tokens brings up a small documentation window for the associated token. In some cases, if there are errors associated with the token that are also displayed the documentation is drawn outside the boundaries of the window and as a result made inaccessible.
___
**Standalone documentation drawn within window boundaries.**

<img width="894" alt="Screen Shot 2022-10-23 at 19 33 36" src="https://user-images.githubusercontent.com/43202406/197406837-07f61bc8-0cd8-47ad-b6ee-2d0af3e0679f.png">

___

**Documentation and error drawn, documentation clips out of the top of the window and cannot be accessed.**

<img width="894" alt="Screen Shot 2022-10-23 at 19 33 24" src="https://user-images.githubusercontent.com/43202406/197406830-38bdbbf5-63e9-400b-a6df-698720e49f2c.png">

### Expected behavior

The documentation is drawn within the window boundaries.

### Environment

Zed 0.61.0 – /Applications/Zed.app
macOS 12.6
architecture x86_64

**Comment by JosephTLyons** [comment]
Thanks for the detailed write up.  We have another issue on this here that has a bit of discussion from one of the team members: 

- https://github.com/zed-industries/feedback/issues/497

Feel free to upvote that one with a 👍 and add any extra details there.  Going to close this one in favor of that one.
