### ISSUE TITLE
Multiple global searches

### ISSUE THREAD

**Issue by ruza-net** [zed-industries/feedback#638]
### Check for existing issues

- [X] Completed

### Is your feature request related to a problem?

When I hit `cmd-shift-f`, a tab with global search opens. If such a tab is already open, the command doesn't open a new one, but switches the the one already open instead.

### Describe the solution you'd like

I'd like if a new search tab be open instead.

### If applicable, add mockups / screenshots to help present your vision of the feature

The motivation is that I like the idea of having a global search for "TODO" open at all times. That way, I can always take a look at what needs doing. However, from time to time, I also need to search for something else, and it's annoying having to open the "TODO" search again and again.

**Comment by JosephTLyons** [comment]
Hey @ruza-net, it is actually possible to have multiple global searches open.  After you open your first global search tab, type in the new search in the input field and hit `cmd-enter`.  We should probably do something to make this action more discoverable.

**Comment by JosephTLyons** [comment]
Here's a related issue:

https://github.com/zed-industries/feedback/issues/464

**Comment by JosephTLyons** [comment]
Im going to go ahead and close this issue in favor of #464

**Comment by ruza-net** [comment]
Oh, didn't know about that. I think that `cmd-shift-f` should still open a new tab (`cmd-enter` requires some setup), but at least having multiple searches is possible.

**Comment by JosephTLyons** [comment]
> Oh, didn't know about that. I think that `cmd-shift-f` should still open a new tab (`cmd-enter` requires some setup), but at least having multiple searches is possible.

Yep, that's what the issue I linked to is all about, allowing new searches to be opened with `cmd-shift-f`.
