### ISSUE TITLE
Don't ask to save when new buffer is split

### ISSUE THREAD

**Issue by gil0mendes** [zed-industries/feedback#639]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When a newly created buffer is split, and we ask to close one of them, Zed will ask if we want to save it first.

### Expected behavior

Since there is a clone of the buffer, there is no need to ask to save.

### Environment

Zed 0.61.1 – /Applications/Zed.app \nmacOS 12.6.1 \narchitecture x86_64

**Comment by JosephTLyons** [comment]
Hey @gil0mendes, looks we have an issue for this already.  Going to close this in favor of that one.  Feel free to upvote it with a 👍 emoji.

- https://github.com/zed-industries/feedback/issues/345
