### ISSUE TITLE
Link to config documentation in default `settings.json` is incorrect

### ISSUE THREAD

**Issue by smbkr** [zed-industries/feedback#644]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The default `settings.json` includes a URL to the config documentation in a comment, however the URL is incorrect. 

It links to `https://zed.dev/docs/configuring-zed`

### Expected behavior

It should link to `https://zed.dev/docs/configuration/configuring-zed`

### Environment

Zed 0.61.1 – /Applications/Zed.app
macOS 12.5.1
architecture arm64

**Comment by JosephTLyons** [comment]
Thanks for the report @smbkr - we've been doing some changes our website routes, which broke this.  Will have it fixed on next release, but until then, the real link is:

https://zed.dev/docs/configuration/configuring-zed
