### ISSUE TITLE
Comment Toggle doesn't work on lines with whitespace only

### ISSUE THREAD

**Issue by TerminalFi** [zed-industries/feedback#654]
### Check for existing issues

- [X] Completed

### Is your feature request related to a problem?

Often times I want to add comments to lines above code. Toggle comment doesn't work unless a line as content and is none whitespace

### Describe the solution you'd like

Allow Toggle Comment to work on any line

**Comment by JosephTLyons** [comment]
Hey @TerminalFi, I remembered seeing an issue for this a long time ago, going to close this one favor of that one, since it already has upvotes on it.  Feel free to upvote it as well!

- https://github.com/zed-industries/feedback/issues/5
