### ISSUE TITLE
HTML support

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/feedback#67]

**Comment by Atelier-Mirai** [comment]
We hope that HTML and CSS will be supported.

**Comment by JosephTLyons** [comment]
> We hope that HTML and CSS will be supported.

We hear you loud and clear.  HTML and CSS will be supported :).  HTML is a bit harder to add because it can embed JavaScript, so Zed has to understand how to parse nested languages.  That being said, work has begun on that front.

**Comment by Atelier-Mirai** [comment]
Thank you for developing a great editor. And thank you for planning to support HTML/CSS in the future. We are looking forward to its release.
