### ISSUE TITLE
Running project search can block the UI

### ISSUE THREAD

**Issue by DarkArc** [zed-industries/feedback#685]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Currently running a full project textual search can lock up the UI (it seems particularly if there are a lot of matches, or perhaps just large files).

### Expected behavior

The full project textual search is unable to block the UI no matter how long the search takes, or how many results there are.

### Environment

Zed 0.63.4 – /Applications/Zed.app \nmacOS 12.6 \narchitecture x86_64

**Comment by DarkArc** [comment]
This seems to be a more general "project search results" issue. I also note that the _normally_ buttery smooth scrolling (even in large files) can be quite sluggish in search results.

**Comment by as-cii** [comment]
This will be fixed in the next release, thanks!

**Comment by DarkArc** [comment]
Thank you :) <3
