### ISSUE TITLE
Multicursor with Arrow Keys

### ISSUE THREAD

**Issue by TerminalFi** [zed-industries/feedback#689]
### Check for existing issues

- [X] Completed

### Is your feature request related to a problem?

Would like to be able to create multiple cursors using the arrow keys with a key binding.

### Describe the solution you'd like

https://user-images.githubusercontent.com/32599364/201491011-5074208d-e261-4e5d-a9ad-c45dbb351c14.mp4

**Comment by fdionisi** [comment]
Hey @TerminalFi, have you already tried `cmd+option+up/down`? If yes, would you mind suggesting how these key bindings could be improved?

**Comment by TerminalFi** [comment]
Hmmm I thought I did. I will try again.

**Comment by JosephTLyons** [comment]
This should be supported @TerminalFi - both with keys and mouse support for adding multiple cursors should exist.  Were you able to get it working on your end?
