### ISSUE TITLE
"Hide Dock" tooltip does not dismiss when mouse is moved

### ISSUE THREAD

**Issue by r0ckwav3** [zed-industries/feedback#718]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When I hover over the "hide dock" button in the bottom right, the tooltip "Hide Dock" appears but then will not disappear when the mouse is removed.

Hovering over the button can reposition the tooltip and notably changing the dock alignment will dismiss the tooltip.

https://user-images.githubusercontent.com/33732392/202938140-ccbbaf68-7fea-43a1-9a97-c074e221ff12.mov

### Expected behavior

When no longer hovering over the button, the "Hide Dock" tooltip should disappear.

### Environment

Zed 0.64.0 – /Applications/Zed.app
macOS 13.0.1
architecture arm64

**Comment by JosephTLyons** [comment]
Thanks for the bug report @r0ckwav3 - it turns out, this issue exists various (all?) UI buttons with tooltips.

**Comment by r0ckwav3** [comment]
A few that I found which didn't have this issue were:
* Project diagnostics
* Go Back

But, as you said, most of the other buttons I tried also have this.

**Comment by JosephTLyons** [comment]
This should be fixed is v0.67.0.  Please reopen if you still have issues in that version or after.
