### ISSUE TITLE
Ability to switch tabs with cmd+number

### ISSUE THREAD

**Issue by Raffo** [zed-industries/feedback#73]
Hi! I would love ask for a feature that I'm completely addicted to in all the editors I use: the ability to switch between tabs with `cmd + number`, similar to what chrome supports. It's something that is wired in my brain and I'd love to propose if this can be on your roadmap. 

Feel free to close this if it doesn't make sense to you of course and keep up the amazing work, so happy to see a fast, native editor!

**Comment by exalted** [comment]
Similar comment-request here: https://github.com/zed-industries/feedback/issues/6#issuecomment-1150111730

**Comment by as-cii** [comment]
We implemented this but went with `ctrl-number` because we're using `cmd-number` to switch between panes. You should be able to customize this in your `keymap.json`  if you prefer Chrome-style tab switching. Thanks for the feedback, @Raffo! 🙏

**Comment by Raffo** [comment]
@as-cii I don't seem to be able to customize the keybindings in the last version (0.50.0). I added to the file:

```
{
        "context": "Workspace",
        "bindings": {
            "cmd-1": [
                "workspace::ActivatePane",
                0
            ],
            "cmd-2": [
                "workspace::ActivatePane",
                1
            ],
            "cmd-3": [
                "workspace::ActivatePane",
                2
            ],
            "cmd-4": [
                "workspace::ActivatePane",
                3
            ],
            "cmd-5": [
                "workspace::ActivatePane",
                4
            ],
            "cmd-6": [
                "workspace::ActivatePane",
                5
            ],
            "cmd-7": [
                "workspace::ActivatePane",
                6
            ],
            "cmd-8": [
                "workspace::ActivatePane",
                7
            ],
            "cmd-9": [
                "workspace::ActivatePane",
                8
            ]
        }
    }
 ```
 
which is just the default config with `ctrl` replaced with `cmd`. I wonder if there is some conflict and if there is a way to validate if the config is applied or not.
