### ISSUE TITLE
cmd+shift+w can't close window

### ISSUE THREAD

**Issue by WindSoilder** [zed-industries/feedback#737]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1. press `cmd+shift+w`
2. current window is not closed

### Expected behavior

current window should be closed

### Environment

Zed 0.65.2 – /Applications/Zed.app \nmacOS 13.0 \narchitecture x86_64

**Comment by JosephTLyons** [comment]
Hey @WindSoilder, are you able to give any more details about the state of the application when you are trying to close the window?  I'm not able to reproduce this one on my end.  Do you have files open?  Sidebars?  Dock?  Also, could try to reproduce it, then check your log file for errors, there might be something there.

**Comment by WindSoilder** [comment]
Oh sorry, I got some other app which is using cmd+shift+w to open it's main panel.

![img](https://user-images.githubusercontent.com/22256154/204204247-8619225d-62f7-4abf-bb91-787e2bc47522.png)

After I close that app, zed works fine on the key.

Sorry for the disturb

**Comment by JosephTLyons** [comment]
> Oh sorry, I got some other app which is using cmd+shift+w to open it's main panel.
> 
> 
> 
> ![img](https://user-images.githubusercontent.com/22256154/204204247-8619225d-62f7-4abf-bb91-787e2bc47522.png)
> 
> 
> 
> After I close that app, zed works fine on the key.
> 
> 
> 
> Sorry for the disturb

No worries @windsokider
