### ISSUE TITLE
Ability to shut off Rust Analyzer at Startup is not working

### ISSUE THREAD

**Issue by stormasm** [zed-industries/feedback#74]
**Describe the bug**

Zed 0.38.0 was supposed to add the ability to turn off the Rust Analyzer at startup,
with a flag in **settings.json** however it does not appear to be working...

**To Reproduce**

Added settings for disabling specific language servers. For example, to turn off Rust-analyzer when editing Rust code, add the following to your ~/.zed/settings.json:

{
    "Rust": {
        "enable_language_server": false
    }
}

**Expected behavior**

When I fire up Zed and start editing some rust code the rust analyzer should not run...

But unfortunately it starts running...

**Environment:**
 - Architecture [Intel, Apple Silicon]:  Intel
 - Mac OS Version: Monterrey 12.2.1
 - Zed Version 0.38.0

**Comment by as-cii** [comment]
Hey @stormasm! To change language-specific settings you have to insert them in the top-level `language_overrides` key. In this case, for example, you'd have to set:

```json
{
    "language_overrides": {
        "Rust": {
            "enable_language_server": false
        }
    }
}
```

Maybe we should show an error when setting a key that doesn't exist? 💭 

Anyway, closing this for now: please, let us know if you still have this issue and feel free to re-open if so. Thanks so much for the feedback!

**Comment by stormasm** [comment]
@as-cii thanks for the heads up on how to fix the **settings.json** file.
I made the change as you suggested and the great news is that
the rust analyzer is now not running...
very cool !
