### ISSUE TITLE
Can't download editor.

### ISSUE THREAD

**Issue by RobiFerentz** [zed-industries/feedback#749]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The Download links in the releases page do not work. I authorized on github after receiving the alpha email. But any download links do not work, getting the github 404 page instead.

### Expected behavior

The download link should lead to an existing downloadable file.

### Environment

echo $(zed --version) "\n"macOS $(sw_vers -productVersion) "\n"architecture $(uname -m)

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![Screenshot 2022-12-01 at 7 00 40](https://user-images.githubusercontent.com/4889861/204969575-4dc111f0-c445-4495-8d9f-e26323fad908.png)

**Comment by JosephTLyons** [comment]
Hey @RobiFerentz, can you try this again?  Attempted to fix this just now.

**Comment by RobiFerentz** [comment]
> Hey @RobiFerentz, really appreciate the report - can you try this again? Attempted to fix this just now.

Yeah, managed to download this time.

**Comment by JosephTLyons** [comment]
> > Hey @RobiFerentz, really appreciate the report - can you try this again? Attempted to fix this just now.
> 
> Yeah, managed to download this time.

Awesome, thanks for the fast feedback.  Can you verify that the build that gets installed is the same one you downloaded from the site?  Just making sure I'm grabbing the proper asset for the download.

**Comment by RobiFerentz** [comment]
> > > Hey @RobiFerentz, really appreciate the report - can you try this again? Attempted to fix this just now.
> > 
> > 
> > Yeah, managed to download this time.
> 
> Awesome, thanks for the fast feedback. Can you verify that the build that gets installed is the same one you downloaded from the site? Just making sure I'm grabbing the proper asset for the download.

Yep. Same version.

**Comment by JosephTLyons** [comment]
Great, thank you so much for the report, we pushed a massive site overhaul and we're expecting some bugs, but we definitely don't want to keep people from downloading stuff.  Really appreciate it.
