### ISSUE TITLE
I'd Like to Contribute

### ISSUE THREAD

**Issue by shellscape** [zed-industries/feedback#764]
I've been following Zed for a while now, and I've been growing increasingly bitter and resentful with Microsoft's iron fist on VS Code. Zed is _almost_ to where I could use it as a daily driver. But there are some quality-of-experience bits that would really make the difference that I'd love to see. Is there a means or mechanism whereby motivated, seasoned engineers like myself could contribute to Zed gratis to further it?

**Comment by JosephTLyons** [comment]
I wish we had a more clear answer than this, but a lot of things are up in the air at this time, including when we might open up the repo.  I added a FAQ just now, in response to this question:

- https://zed.dev/faq#how-can-i-contribute

**Comment by shellscape** [comment]
If legal would approve, and there was sufficient bandwidth to manage it, might the company be open to volunteers with a signed NDA or some such?
