### ISSUE TITLE
Recent projects browser

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/feedback#77]
**Is your feature request related to a problem? Please describe.**
Browsing for projects within the macOS file browser is ok, but it is a bit slow to summon.

**Describe the solution you'd like**
I would really like having some way to reopen recently opened projects.  This could be something as simple as VS Code's `File > Open Recent`, but what I would really like is a command that opens a modal that you can fuzzy search through the last `n` recently opened projects.  `n` could be a hardcoded number, like 50, or it could be defined via a setting.  Something about being able to browse and open projects, at the speed in which you can `command+p` a file, sounds really satisfying.

**Comment by imron** [comment]
File > Open Recent is common to almost every mac application that has the concept of a "Document", and this is a feature I would like to see.

Having a more advanced modal with fuzzy search also sounds useful.  Perhaps both can be supported?

**Comment by JosephTLyons** [comment]
> File > Open Recent is common to almost every mac application that has the concept of a "Document", and this is a feature I would like to see.
> 
> Having a more advanced modal with fuzzy search also sounds useful. Perhaps both can be supported?

I like the idea of both 🙂

**Comment by iamnbutler** [comment]
`File > Open Recent` will be added, just didn't make it into the first pass of low hanging fruit menu bar items. I'd also love this.

Otherwise, I have a lot of ideas around how to surface your common/recent projects or ones you have recently joined, but those will depend more on the other surfaces we decide to add. A projects panel for example (not to be confused with the _project_ panel 😁)

**Comment by mikayla-maki** [comment]
Blocks on: https://github.com/zed-industries/feedback/issues/430

**Comment by uicrafts** [comment]
This would be great to have when using `CMD+P` -> by default show the most recently opened files to quickly jump to them, like VSCode.

**Comment by JosephTLyons** [comment]
A recent project picker has been added and should go out in v0.68.0.  Its such an awesome thing to open projects in the same way you'd open files with `cmd-p`!
