### ISSUE TITLE
Not able to install Zed properly

### ISSUE THREAD

**Issue by uzaxirr** [zed-industries/feedback#776]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I've downloaded the zed dmg file after getting the invite. And when i open the dmg file i get no option to move it to Applications just like we get in other apps.
<img width="924" alt="Screenshot 2022-12-09 at 10 44 04 PM" src="https://user-images.githubusercontent.com/72073401/206756628-bc924012-eda8-4c09-a1af-51327484be44.png">

I see no installed application by the name `zed` whenever i shut down my computer. Please do let me know if i'm doing anything wrong

### Environment

<img width="862" alt="Screenshot 2022-12-09 at 10 47 02 PM" src="https://user-images.githubusercontent.com/72073401/206757109-728240c4-50c2-43fe-b2a0-c8f19fabb0ce.png">

**Comment by mikayla-maki** [comment]
Hi Uzaxirr, we're going to be fixing that step of the install soon, so sorry for the trouble! If you open another finder window, you can drag the Zed app to the applications folder manually. Then once it's installed you can open it and select 'install Zed CLI' from the 'Zed Preview' window :D

**Comment by JosephTLyons** [comment]
Im going to leave this open until I add the code that puts the symlink in the dmg.  That should make things a bit more clear on how to install.

**Comment by JosephTLyons** [comment]
A symlink will be added into the DMG in v0.68.0.  This should make it a bit easier to understand how to install the application.
