### ISSUE TITLE
Global project search returns no results

### ISSUE THREAD

**Issue by vaidotasp** [zed-industries/feedback#780]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Global search (CMD+SHIFT+F) results are always empty. I tried opening zed via CLI in my project dir `zed .`, I also tried opening my project with CMD+O. Same results.

Not sure what other things I can try. Any help would be appreciated 👍 

### Environment

Zed 0.66.0 – /Applications/Zed.app
macOS 13.0.1
architecture arm64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="1252" alt="image" src="https://user-images.githubusercontent.com/12076555/207269582-58604afc-fff3-403b-9da7-5d99418d567c.png">

<img width="994" alt="image" src="https://user-images.githubusercontent.com/12076555/207269687-12dc39f4-73c8-48c9-9c7e-c71ce2f651fc.png">

**Comment by JosephTLyons** [comment]
This is a very strange issue.  Are there any errors in your Zed.log file that appear right after attempting to search?

To see the log: command palette > `zed: open log`

**Comment by vaidotasp** [comment]
Hey, nothing too significant seems to be happening. Maybe permission issue on the OS level or some conflict with other things installed 🤔 

My settings:

```
{
    "theme": "One Dark",
    "buffer_font_size": 17,
    "vim_mode": true,
    "experiments": {
        "experimental_themes": true
    },
    "cursor_blink": false,
    "preferred_line_length": 80
}
```


<img width="883" alt="image" src="https://user-images.githubusercontent.com/12076555/207518050-6a217f7c-d362-48e2-b103-db4130781120.png">

**Comment by JosephTLyons** [comment]
Another question, does this happen in every single project you open in Zed, or just a few particular ones?  If you haven't tried, would you mind opening some projects in various locations?

**Comment by maxbrunsfeld** [comment]
From the screenshot of your project panel, it looks like Zed thinks that all of the directories in your project are ignored in git. What does your `.gitignore` file contain?

**Comment by vaidotasp** [comment]
Okay that explains it! I have a bit of a weird "dotfile management" setup. I have git repository initiated at the root of my file system and I have a `.gitignore` over there allowing only specific files/folders that I sync with my github repo.

So looks like Zed is picking up that root `.gitignore` no matter how deep within file system my project is and ignoring project's own git repo.

**Comment by vaidotasp** [comment]
Upon search through the issues related to `.gitignore` I think my problem is exactly as https://github.com/zed-industries/feedback/issues/575.

Closing this.
