### ISSUE TITLE
Rust language server no longer working

### ISSUE THREAD

**Issue by bho01** [zed-industries/feedback#782]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

For a long time the bottom right corner indicated that is was downloading the rust language server. I closed Zed and reopened it and now none of the rust language features work such as:
error checking
hovering over something to see more information
auto complete suggestions

### Environment

Zed 0.66.0 – /Applications/Zed.app 
macOS 12.5 
architecture arm64

**Comment by JosephTLyons** [comment]
Hey @bho01, does anything show up in your log file when opening a Rust project?  You can view the last 1000 lines of the log file in Zed by running the `zed: open log` command in the command palette.  Also, there is an `editor: restart language server` action to restart the language server, maybe try running that a couple of times and see if anything shows in the log file.

**Comment by bho01** [comment]
Hello @JosephTLyons I see a lot of these when I open the log file:

02:49:18 [WARN] request completed with error: unknown error
02:49:20 [INFO] set status on client 0: Reauthenticating
02:49:20 [INFO] set status on client 0: Reconnecting
02:50:36 [INFO] set status on client 0: ConnectionError
02:50:36 [ERROR] failed to connect timed out trying to establish connection
02:50:36 [INFO] set status on client 0: ReconnectionError { next_reconnection: Instant { t: 8745818059313 } }.

I will try the restart and report back.

Thank you

bho01

**Comment by bho01** [comment]
The language server reset did not seem to do anything either.

**Comment by JosephTLyons** [comment]
@bho01, can you try:

1. Closing Zed
2. Deleting the language servers out of the [language server directory](https://zed.dev/faq#where-are-language-servers-stored?)
3. Reopening Zed

**Comment by bho01** [comment]
@JosephTLyons it seems to work now that I do that. Thank you...

**Comment by JosephTLyons** [comment]
@bho01 - awesome.  It seems that once in awhile, the binaries can have issues when being downloaded and installed.  We probably need a better way to handle this going forward.

**Comment by LimingFang** [comment]
I met the same problem. When I first open a `.rs` file, zed began to download rust-analyser, but I close zed by accident. I found the rust-analyser is only 14MB, however, after I did what you said , the rust-analyser is about 30MB. So maybe zed should be able to handle unexpected exits
