### ISSUE TITLE
Allow the user to manually specify a language

### ISSUE THREAD

**Issue by natejank** [zed-industries/feedback#793]
### Check for existing issues

- [x] Completed

### Describe the feature

I have a build script written in python, without the .py file extension.  I didn't see any ability to manually specify a language (so I could use it as a python file) so I don't get any language features.  Either a command palette option and/or a menu button to select a language would be useful.

It's also worth mentioning that it has `#!/usr/bin/env python3` at the beginning of the file to specify the interpreter, but this also isn't detected by Zed.

**Comment by JosephTLyons** [comment]
Hey @natejank, this is a popular request - not sure when we might get around to it, but it seems like something we will do in time.  We have an open issue for it with a handful of votes on it, so I'm going to close this one to keeps all the votes on one issue.  Would you mind upvoting this one?

- https://github.com/zed-industries/feedback/issues/207

**Comment by natejank** [comment]
I somehow didn't catch that issue (oops sorry), but thank you!
