### ISSUE TITLE
sticky scroll

### ISSUE THREAD

**Issue by zhylmzr** [zed-industries/feedback#799]
### Check for existing issues

- [X] Completed

### Describe the feature

This feature can quickly locate the context of the current line.

VSCode:
<img width="689" alt="SCR-20221221-el4" src="https://user-images.githubusercontent.com/15730824/208806459-91a4a8c7-7a1c-4b51-ae59-0d381095c55f.png">

**Comment by JosephTLyons** [comment]
Hey @zhylmzr,

I think we have another issue that covers this request here: https://github.com/zed-industries/feedback/issues/141

Going to close this one out.  Feel free to upvote the original to bring more attention to it.
