### ISSUE TITLE
Add support for `home` and `end` keys in keymap

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/feedback#806]
### Check for existing issues

- [X] Completed

### Describe the feature

The default keymap should have:

`"home": "editor::MoveToBeginningOfLine"`
`"end": "editor::MoveToEndOfLine"`

**Comment by velipso** [comment]
duplicate of #715

**Comment by JosephTLyons** [comment]
I can't believe what I've done 🤣 thanks for letting me know @velipso!
