### ISSUE TITLE
Minor docs issue: tab_size is erroneously written as tab-size

### ISSUE THREAD

**Issue by exalted** [zed-industries/feedback#81]
Here https://zed.dev/docs/configuring-zed, in "Available settings" section, `tab_size` option is written as `tab-size` (with a hyphen rather than an underscore).

**Comment by iamnbutler** [comment]
Fixed! (Vercel is being weird right now, but you should see the change whenever the deployment lands!)

**Comment by iamnbutler** [comment]
Thanks for the catch! In the future these will be autogenerated so we shouldn't have these sort of issues :)

**Comment by exalted** [comment]
@iamnbutler no worries, at all! I was just being picky is all… You're doing GREAT work, keep rockin'!
