### ISSUE TITLE
buffer symbols are corrupted

### ISSUE THREAD

**Issue by TENX-S** [zed-industries/feedback#834]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/40336192/211156563-47ad7f2b-e7b4-4c47-8533-18498d7ff5f9.png">

### Environment

Zed 0.67.5 – /Applications/Zed.app
macOS 13.1
architecture arm64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue

[Zed.log](https://github.com/zed-industries/feedback/files/10366523/Zed.log)

**Comment by JosephTLyons** [comment]
Hey @TENX-S, are you able to provide a project with some minimal amount of code that reproduces the issue?  I know its al to to ask, but its pretty hard to diagnose things like this from afar without any code.

**Comment by TENX-S** [comment]
main.go:
```go
package main

type ListPointReq struct {
	route      string `path:"/data/point/list/{DeviceCode}" method:"post" summary:"查询测点" tags:"数据一览"`
	DeviceCode string `in:"path" dc:"设备编码" d:"default_0053"`
	Limit      struct {
		Page  int    `json:"page"`
		Limit int    `json:"limit"`
		Order string `json:"order"`
		Sort  string `json:"sort"`
	} `json:"limit"`
	Filter struct {
		Node    string `json:"node"`
		Keyword string `json:"keyword"`
		ID      string `json:"ID"`
		DS      int    `json:"DS"`
	} `json:"filter"`
}

func main() {}
```
