### ISSUE TITLE
Svelte Support

### ISSUE THREAD

**Issue by jakobbouchard** [zed-industries/feedback#836]
### Check for existing issues

- [X] Completed

### Language

Svelte

### Tree Sitter parser link

https://github.com/Himujjal/tree-sitter-svelte

### Language server link

https://github.com/sveltejs/language-tools

**Comment by JosephTLyons** [comment]
Hey @jakobbouchard, we have an issue for this with a handful of upvotes on it already.  I'm going to close this one in favor of that one.  Would you mind upvoting that issue instead?

https://github.com/zed-industries/feedback/issues/432

**Comment by jakobbouchard** [comment]
Oh for sure, I must’ve been tired when I did this, as I was sure I searched for it 😅 Sorry for the duplicate!

**Comment by itsezc** [comment]
@JosephTLyons  Could we reopen this issue or make #432 public?
