### ISSUE TITLE
Settings don't apply

### ISSUE THREAD

**Issue by brachkow** [zed-industries/feedback#852]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

TLDR; Tried to change Zed settings and nothing happened.

Went to `File > Settings > Open Settings` and changed it to this
```json
{
    "buffer_font_size": 12,
    "buffer_font_family": "JetBrains Mono",
    "cursor_blink": false,
}
```
but font size and family is still default, and cursor is blinking.

Tried relaunching — no changes either.

### Environment

Zed 0.68.1 – /Applications/Zed.app
macOS 13.1
architecture arm64

**Comment by Pringlers** [comment]
Your snippet has trailing comma after `false`, which is invalid in JSON. Check if it works without it

**Comment by brachkow** [comment]
Yes, now it works.

It is of course is a stupid typo error, but I never stuck because of it in sublime for example.

So I think it will be cool to add some validation message to editor interface.
