### ISSUE TITLE
HCL support

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/feedback#857]
### Check for existing issues

- [X] Completed

### Language

HashiCorp Configuration Language

### Tree Sitter parser link

https://github.com/mitchellh/tree-sitter-hcl

### Language server link

https://github.com/hashicorp/terraform-ls

**Comment by fdionisi** [comment]
This looks like a duplicate of https://github.com/zed-industries/feedback/issues/747

**Comment by JosephTLyons** [comment]
Oh yeah!  Super nice catch!  Totally forgot about that previous issue!  Thanks @fdionisi!
