### ISSUE TITLE
YAML sytax highlighting

### ISSUE THREAD

**Issue by AssertionBit** [zed-industries/feedback#862]
### Check for existing issues

- [x] Completed

### Language

YAML

### Tree Sitter parser link

https://github.com/ikatyang/tree-sitter-yaml

### Language server link

https://github.com/adamvoss/vscode-yaml-languageservice

**Comment by hovsater** [comment]
@AssertionBit there's already an issue tracking that. See https://github.com/zed-industries/feedback/issues/251.

**Comment by AssertionBit** [comment]
Thanks! Closing this issue
