### ISSUE TITLE
Documentation typo (rate-limiteed)

### ISSUE THREAD

**Issue by MultisampledNight** [zed-industries/feedback#864]
https://zed.dev/docs/general/telemetry lists

> requests are **rate-limiteed** to avoid using significant network bandwidth

<3

(slightly related to #865 should that section be reworded)

**Comment by JosephTLyons** [comment]
Thanks for catching this @MultisampledNight, fix should be up shortly.

https://github.com/zed-industries/zed.dev/commit/c02011923517ba7075a03b506bcc276d33d8e849
