### ISSUE TITLE
Sub word boundary navigation

### ISSUE THREAD

**Issue by MoritzKn** [zed-industries/feedback#868]
### Check for existing issues

- [X] Completed

### Describe the feature

The ability to navigate between "sub-word" boundaries. Each word in a CamleCase string would be separated by a subword boundary. Same with CONSTANT_CASE or snake_case.

In VS Code this is only possible with an [extension](https://marketplace.visualstudio.com/items?itemName=OlleWestman.SubwordNavigation). Atom supported this natively.

**Comment by caius** [comment]
Pretty sure this already exists, although I'm not sure there's a default macOS keybinding to make it discoverable.

In my [TextMate inspired keymap](https://github.com/caius/zed-keymaps/blob/textmate/textmate/keymap.json#L36-L37) I've bound moving by subword boundary to control-left & control-right respectively.

```json
      "ctrl-left": "editor::MoveToPreviousSubwordStart",
      "ctrl-right": "editor::MoveToNextSubwordEnd",
```

Looks like the [default keymap](https://zed.dev/ref/default.json) has them defined as control-alt-left & control-alt-right.

**Comment by MoritzKn** [comment]
You are right, thank you!
