### ISSUE TITLE
Allow for arbitrary command to run for format_on_save hook

### ISSUE THREAD

**Issue by max** [zed-industries/feedback#91]
**Is your feature request related to a problem? Please describe.**
I use Prettier for JavaScript/Markdown code formatting and Zed does not support Prettier.

**Describe the solution you'd like**
I'd like to be able to run an arbitrary command when `format_on_save` is called.

**Comment by maxbrunsfeld** [comment]
Another use-case for this is [formatting Python code with Black](https://github.com/zed-industries/feedback/issues/66#issuecomment-1159338863); the Python language server that we're using, Pyright, does not provide code formatting.

**Comment by as-cii** [comment]
We just finished implementing this and it'll go out with the next release of Zed. Thanks so much for the feedback! 🙏
