### ISSUE TITLE
Prevent some directories from automatically expanding in the sidebar

### ISSUE THREAD

**Issue by postrsocial** [zed-industries/feedback#914]
### Check for existing issues

- [X] Completed

## Steps

1. Open a TypeScript project with a `node_modules` directory.
2. Use Zed's _Go To Definition_ to go to a type definition located in `node_modules`.

## Actual Behavior

The sidebar expands `node_modules`, creating a ripple in spacetime.

## Desired Behavior

The sidebar does not expand `node_modules` because I've added `node_modules` to some kind of exclusion list.

**Comment by JosephTLyons** [comment]
Hey @postrsocial, this thing has burned us all.  This could certainly use a setting.  We do have another issue open tracking this.  Would you mind putting a 👍 on that one so we can collect the upvotes in one place?  I'm going to close this one out.

https://github.com/zed-industries/feedback/issues/800

**Comment by postrsocial** [comment]
Sorry about that; I only searched the existing issues for "sidebar". I'll add a 👍 to #800.

**Comment by JosephTLyons** [comment]
Absolutely no worries at all!  I'd rather you report something as a duplicate than not report it!  I make duplicate issues all the time 🤣.
