### ISSUE TITLE
show wrap guide at prefererred line length

### ISSUE THREAD

**Issue by cpollett** [zed-industries/feedback#917]
### Check for existing issues

- [ ] Completed

### Describe the feature

First up, I really like Zed -- it's very fast. The two things that are blocking me from using it as my default editor are not being able to see invisibles (which is already requested in #308), and  that there is no wrap guide at the preferred line length. For me, this would appear as a soft-gray line at column 80. Thanks Zed team for you hard work on this project!

Best,

Chris

**Comment by cpollett** [comment]
Duplicate of #58

**Comment by JosephTLyons** [comment]
Thanks @cpollett, no worries on the duplicate post, happens all the time to me!  Would you mind upvoting the original with a 👍 emoji?  That will help us with prioritizing it.  Going to close this one out.
