### ISSUE TITLE
Unable to download Zed from the website

### ISSUE THREAD

**Issue by rranjan14** [zed-industries/feedback#921]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Unable to download zed dmg file from the website.

### Environment

Software:

    System Software Overview:

      System Version: macOS 13.2 (22D49)
      Kernel Version: Darwin 22.3.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal

Hardware:

    Hardware Overview:

      Model Name: MacBook Air
      Model Identifier: MacBookAir10,1
      Model Number: MGN63HN/A
      Chip: Apple M1
      Total Number of Cores: 8 (4 performance and 4 efficiency)
      Memory: 8 GB

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by petros** [comment]
Thank you for reporting this. Could you share a few more details? I have tried here and it works currently. Can you try a different network?

**Comment by rranjan14** [comment]
Has been solved. Closing the issues.
